// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct PerformanceMeasureRustMethods {
  pub version: c_double,
  pub performance_entry: PerformanceEntryRustMethods,
  pub detail: extern "C" fn(ptr: *const OpaquePtr) -> NativeValue,
}
pub struct PerformanceMeasure {
  pub performance_entry: PerformanceEntry,
  method_pointer: *const PerformanceMeasureRustMethods,
}
impl PerformanceMeasure {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const PerformanceMeasureRustMethods, status: *const RustValueStatus) -> PerformanceMeasure {
    unsafe {
      PerformanceMeasure {
        performance_entry: PerformanceEntry::initialize(
          ptr,
          context,
          &(method_pointer).as_ref().unwrap().performance_entry,
          status,
        ),
        method_pointer,
      }
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.performance_entry.ptr()
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    self.performance_entry.context()
  }
  pub fn detail(&self) -> NativeValue {
    let value = unsafe {
      ((*self.method_pointer).detail)(self.ptr())
    };
    value
  }
}
pub trait PerformanceMeasureMethods: PerformanceEntryMethods {
  fn detail(&self) -> NativeValue;
  fn as_performance_measure(&self) -> &PerformanceMeasure;
}
impl PerformanceMeasureMethods for PerformanceMeasure {
  fn detail(&self) -> NativeValue {
    self.detail()
  }
  fn as_performance_measure(&self) -> &PerformanceMeasure {
    self
  }
}
impl PerformanceEntryMethods for PerformanceMeasure {
  fn name(&self) -> String {
    self.performance_entry.name()
  }
  fn entry_type(&self) -> String {
    self.performance_entry.entry_type()
  }
  fn start_time(&self) -> i64 {
    self.performance_entry.start_time()
  }
  fn duration(&self) -> i64 {
    self.performance_entry.duration()
  }
  fn to_json(&self, exception_state: &ExceptionState) -> Result<NativeValue, String> {
    self.performance_entry.to_json(exception_state)
  }
  fn as_performance_entry(&self) -> &PerformanceEntry {
    &self.performance_entry
  }
}
