name: webf_video_player
description: WebF Video Player module for handling video playback with Flutter video_player
version: 0.1.0-beta
homepage: https://openwebf.com

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webf: 
    hosted: https://dart.cloudsmith.io/openwebf/webf-enterprise/
    version: ^0.23.0-beta.3
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

# Information used by the publishing tool.
publish_to: https://dart.cloudsmith.io/openwebf/webf-video-player/

topics:
  - webf
  - video
  - player
  - media
  - flutter