// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct PromiseRejectionEventRustMethods {
  pub version: c_double,
  pub event: EventRustMethods,
  pub promise: extern "C" fn(*const OpaquePtr, *const OpaquePtr) -> NativeValue,
  pub reason: extern "C" fn(*const OpaquePtr, *const OpaquePtr) -> NativeValue,
}
pub struct PromiseRejectionEvent {
  pub event: Event,
  method_pointer: *const PromiseRejectionEventRustMethods,
}
impl PromiseRejectionEvent {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const PromiseRejectionEventRustMethods, status: *const RustValueStatus) -> PromiseRejectionEvent {
    unsafe {
      PromiseRejectionEvent {
        event: Event::initialize(
          ptr,
          context,
          &(method_pointer).as_ref().unwrap().event,
          status,
        ),
        method_pointer,
      }
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.event.ptr()
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    self.event.context()
  }
  pub fn promise(&self, exception_state: &ExceptionState) -> NativeValue {
    let value = unsafe {
      ((*self.method_pointer).promise)(self.ptr(), exception_state.ptr)
    };
    value
  }
  pub fn reason(&self, exception_state: &ExceptionState) -> NativeValue {
    let value = unsafe {
      ((*self.method_pointer).reason)(self.ptr(), exception_state.ptr)
    };
    value
  }
}
pub trait PromiseRejectionEventMethods: EventMethods {
  fn promise(&self, exception_state: &ExceptionState) -> NativeValue;
  fn reason(&self, exception_state: &ExceptionState) -> NativeValue;
  fn as_promise_rejection_event(&self) -> &PromiseRejectionEvent;
}
impl PromiseRejectionEventMethods for PromiseRejectionEvent {
  fn promise(&self, exception_state: &ExceptionState) -> NativeValue {
    self.promise(exception_state)
  }
  fn reason(&self, exception_state: &ExceptionState) -> NativeValue {
    self.reason(exception_state)
  }
  fn as_promise_rejection_event(&self) -> &PromiseRejectionEvent {
    self
  }
}
impl EventMethods for PromiseRejectionEvent {
  fn bubbles(&self) -> bool {
    self.event.bubbles()
  }
  fn cancel_bubble(&self) -> bool {
    self.event.cancel_bubble()
  }
  fn set_cancel_bubble(&self, value: bool, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.set_cancel_bubble(value, exception_state)
  }
  fn cancelable(&self) -> bool {
    self.event.cancelable()
  }
  fn current_target(&self) -> EventTarget {
    self.event.current_target()
  }
  fn default_prevented(&self) -> bool {
    self.event.default_prevented()
  }
  fn src_element(&self) -> EventTarget {
    self.event.src_element()
  }
  fn target(&self) -> EventTarget {
    self.event.target()
  }
  fn is_trusted(&self) -> bool {
    self.event.is_trusted()
  }
  fn time_stamp(&self) -> f64 {
    self.event.time_stamp()
  }
  fn type_(&self) -> String {
    self.event.type_()
  }
  fn init_event(&self, type_: &str, bubbles: bool, cancelable: bool, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.init_event(type_, bubbles, cancelable, exception_state)
  }
  fn prevent_default(&self, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.prevent_default(exception_state)
  }
  fn stop_immediate_propagation(&self, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.stop_immediate_propagation(exception_state)
  }
  fn stop_propagation(&self, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.stop_propagation(exception_state)
  }
  fn as_event(&self) -> &Event {
    &self.event
  }
}
impl ExecutingContext {
  pub fn create_promise_rejection_event(&self, event_type: &str, exception_state: &ExceptionState) -> Result<PromiseRejectionEvent, String> {
    let event_type_c_string = CString::new(event_type).unwrap();
    let new_event = unsafe {
      ((*self.method_pointer()).create_promise_rejection_event)(self.ptr, event_type_c_string.as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self));
    }
    return Ok(PromiseRejectionEvent::initialize(new_event.value, self, new_event.method_pointer, new_event.status));
  }
  pub fn create_promise_rejection_event_with_options(&self, event_type: &str, options: &PromiseRejectionEventInit,  exception_state: &ExceptionState) -> Result<PromiseRejectionEvent, String> {
    let event_type_c_string = CString::new(event_type).unwrap();
    let new_event = unsafe {
      ((*self.method_pointer()).create_promise_rejection_event_with_options)(self.ptr, event_type_c_string.as_ptr(), options, exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self));
    }
    return Ok(PromiseRejectionEvent::initialize(new_event.value, self, new_event.method_pointer, new_event.status));
  }
}
