// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_ANIMATION_EVENT_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_ANIMATION_EVENT_H_
#include <stdint.h>
#include "core/native/vector_value_ref.h"
#include "rust_readable.h"
#include "event.h"
namespace webf {
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
typedef struct AtomicStringRef AtomicStringRef;
class AnimationEvent;
using PublicAnimationEventGetAnimationName = AtomicStringRef (*)(AnimationEvent*);
using PublicAnimationEventGetElapsedTime = double (*)(AnimationEvent*);
using PublicAnimationEventGetPseudoElement = AtomicStringRef (*)(AnimationEvent*);
struct AnimationEventPublicMethods : public WebFPublicMethods {
  static AtomicStringRef AnimationName(AnimationEvent* animation_event);
  static double ElapsedTime(AnimationEvent* animation_event);
  static AtomicStringRef PseudoElement(AnimationEvent* animation_event);
  double version{1.0};
  EventPublicMethods event;
  PublicAnimationEventGetAnimationName animation_event_get_animation_name{AnimationName};
  PublicAnimationEventGetElapsedTime animation_event_get_elapsed_time{ElapsedTime};
  PublicAnimationEventGetPseudoElement animation_event_get_pseudo_element{PseudoElement};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_ANIMATION_EVENT_H_
