// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_HASHCHANGE_EVENT_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_HASHCHANGE_EVENT_H_
#include <stdint.h>
#include "script_value_ref.h"
#include "event.h"
namespace webf {
class SharedExceptionState;
class ExecutingContext;
class HashchangeEvent;
typedef struct ScriptValueRef ScriptValueRef;
using PublicHashchangeEventGetNewURL = const char* (*)(HashchangeEvent*);
using PublicHashchangeEventDupNewURL = const char* (*)(HashchangeEvent*);
using PublicHashchangeEventGetOldURL = const char* (*)(HashchangeEvent*);
using PublicHashchangeEventDupOldURL = const char* (*)(HashchangeEvent*);
struct HashchangeEventPublicMethods : public WebFPublicMethods {
  static const char* NewURL(HashchangeEvent* hashchange_event);
  static const char* DupNewURL(HashchangeEvent* hashchange_event);
  static const char* OldURL(HashchangeEvent* hashchange_event);
  static const char* DupOldURL(HashchangeEvent* hashchange_event);
  double version{1.0};
  EventPublicMethods event;
  PublicHashchangeEventGetNewURL hashchange_event_get_new_url{NewURL};
  PublicHashchangeEventDupNewURL hashchange_event_dup_new_url{DupNewURL};
  PublicHashchangeEventGetOldURL hashchange_event_get_old_url{OldURL};
  PublicHashchangeEventDupOldURL hashchange_event_dup_old_url{DupOldURL};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_HASHCHANGE_EVENT_H_
