// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_HTML_IMAGE_ELEMENT_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_HTML_IMAGE_ELEMENT_H_
#include <stdint.h>
#include "core/native/vector_value_ref.h"
#include "rust_readable.h"
#include "html_element.h"
namespace webf {
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
typedef struct AtomicStringRef AtomicStringRef;
class HTMLImageElement;
using PublicHTMLImageElementGetAlt = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementSetAlt = void (*)(HTMLImageElement*, const char*, SharedExceptionState*);
using PublicHTMLImageElementGetSrc = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementSetSrc = void (*)(HTMLImageElement*, const char*, SharedExceptionState*);
using PublicHTMLImageElementGetSizes = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementSetSizes = void (*)(HTMLImageElement*, const char*, SharedExceptionState*);
using PublicHTMLImageElementGetWidth = int64_t (*)(HTMLImageElement*);
using PublicHTMLImageElementSetWidth = void (*)(HTMLImageElement*, int64_t, SharedExceptionState*);
using PublicHTMLImageElementGetHeight = int64_t (*)(HTMLImageElement*);
using PublicHTMLImageElementSetHeight = void (*)(HTMLImageElement*, int64_t, SharedExceptionState*);
using PublicHTMLImageElementGetNaturalWidth = int64_t (*)(HTMLImageElement*);
using PublicHTMLImageElementGetNaturalHeight = int64_t (*)(HTMLImageElement*);
using PublicHTMLImageElementGetComplete = int32_t (*)(HTMLImageElement*);
using PublicHTMLImageElementGetCurrentSrc = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementGetDecoding = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementSetDecoding = void (*)(HTMLImageElement*, const char*, SharedExceptionState*);
using PublicHTMLImageElementGetFetchPriority = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementSetFetchPriority = void (*)(HTMLImageElement*, const char*, SharedExceptionState*);
using PublicHTMLImageElementGetLoading = AtomicStringRef (*)(HTMLImageElement*);
using PublicHTMLImageElementSetLoading = void (*)(HTMLImageElement*, const char*, SharedExceptionState*);
struct HTMLImageElementPublicMethods : public WebFPublicMethods {
  static AtomicStringRef Alt(HTMLImageElement* html_image_element);
  static void SetAlt(HTMLImageElement* html_image_element, const char* alt, SharedExceptionState* shared_exception_state);
  static AtomicStringRef Src(HTMLImageElement* html_image_element);
  static void SetSrc(HTMLImageElement* html_image_element, const char* src, SharedExceptionState* shared_exception_state);
  static AtomicStringRef Sizes(HTMLImageElement* html_image_element);
  static void SetSizes(HTMLImageElement* html_image_element, const char* sizes, SharedExceptionState* shared_exception_state);
  static int64_t Width(HTMLImageElement* html_image_element);
  static void SetWidth(HTMLImageElement* html_image_element, int64_t width, SharedExceptionState* shared_exception_state);
  static int64_t Height(HTMLImageElement* html_image_element);
  static void SetHeight(HTMLImageElement* html_image_element, int64_t height, SharedExceptionState* shared_exception_state);
  static int64_t NaturalWidth(HTMLImageElement* html_image_element);
  static int64_t NaturalHeight(HTMLImageElement* html_image_element);
  static int32_t Complete(HTMLImageElement* html_image_element);
  static AtomicStringRef CurrentSrc(HTMLImageElement* html_image_element);
  static AtomicStringRef Decoding(HTMLImageElement* html_image_element);
  static void SetDecoding(HTMLImageElement* html_image_element, const char* decoding, SharedExceptionState* shared_exception_state);
  static AtomicStringRef FetchPriority(HTMLImageElement* html_image_element);
  static void SetFetchPriority(HTMLImageElement* html_image_element, const char* fetchPriority, SharedExceptionState* shared_exception_state);
  static AtomicStringRef Loading(HTMLImageElement* html_image_element);
  static void SetLoading(HTMLImageElement* html_image_element, const char* loading, SharedExceptionState* shared_exception_state);
  double version{1.0};
  HTMLElementPublicMethods html_element;
  PublicHTMLImageElementGetAlt html_image_element_get_alt{Alt};
  PublicHTMLImageElementSetAlt html_image_element_set_alt{SetAlt};
  PublicHTMLImageElementGetSrc html_image_element_get_src{Src};
  PublicHTMLImageElementSetSrc html_image_element_set_src{SetSrc};
  PublicHTMLImageElementGetSizes html_image_element_get_sizes{Sizes};
  PublicHTMLImageElementSetSizes html_image_element_set_sizes{SetSizes};
  PublicHTMLImageElementGetWidth html_image_element_get_width{Width};
  PublicHTMLImageElementSetWidth html_image_element_set_width{SetWidth};
  PublicHTMLImageElementGetHeight html_image_element_get_height{Height};
  PublicHTMLImageElementSetHeight html_image_element_set_height{SetHeight};
  PublicHTMLImageElementGetNaturalWidth html_image_element_get_natural_width{NaturalWidth};
  PublicHTMLImageElementGetNaturalHeight html_image_element_get_natural_height{NaturalHeight};
  PublicHTMLImageElementGetComplete html_image_element_get_complete{Complete};
  PublicHTMLImageElementGetCurrentSrc html_image_element_get_current_src{CurrentSrc};
  PublicHTMLImageElementGetDecoding html_image_element_get_decoding{Decoding};
  PublicHTMLImageElementSetDecoding html_image_element_set_decoding{SetDecoding};
  PublicHTMLImageElementGetFetchPriority html_image_element_get_fetch_priority{FetchPriority};
  PublicHTMLImageElementSetFetchPriority html_image_element_set_fetch_priority{SetFetchPriority};
  PublicHTMLImageElementGetLoading html_image_element_get_loading{Loading};
  PublicHTMLImageElementSetLoading html_image_element_set_loading{SetLoading};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_HTML_IMAGE_ELEMENT_H_
