// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_INPUT_EVENT_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_INPUT_EVENT_H_
#include <stdint.h>
#include "rust_readable.h"
#include "ui_event.h"
namespace webf {
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
typedef struct AtomicStringRef AtomicStringRef;
class InputEvent;
using PublicInputEventGetInputType = AtomicStringRef (*)(InputEvent*);
using PublicInputEventGetData = AtomicStringRef (*)(InputEvent*);
struct InputEventPublicMethods : public WebFPublicMethods {
  static AtomicStringRef InputType(InputEvent* input_event);
  static AtomicStringRef Data(InputEvent* input_event);
  double version{1.0};
  UIEventPublicMethods ui_event;
  PublicInputEventGetInputType input_event_get_input_type{InputType};
  PublicInputEventGetData input_event_get_data{Data};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_INPUT_EVENT_H_
