// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_LEGACY_CSS_STYLE_DECLARATION_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_LEGACY_CSS_STYLE_DECLARATION_H_
#include <stdint.h>
#include "core/native/vector_value_ref.h"
#include "rust_readable.h"
#include "webf_value.h"
namespace webf {
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
typedef struct AtomicStringRef AtomicStringRef;
namespace legacy {
class LegacyCssStyleDeclaration;
}
using LegacyCssStyleDeclaration = legacy::LegacyCssStyleDeclaration;
enum class LegacyCssStyleDeclarationType {
  kLegacyCssStyleDeclaration = 0,
  kLegacyComputedCssStyleDeclaration = 1,
  kLegacyInlineCssStyleDeclaration = 2,
};
using PublicLegacyCssStyleDeclarationGetCssText = AtomicStringRef (*)(LegacyCssStyleDeclaration*);
using PublicLegacyCssStyleDeclarationSetCssText = void (*)(LegacyCssStyleDeclaration*, const char*, SharedExceptionState*);
using PublicLegacyCssStyleDeclarationGetLength = int64_t (*)(LegacyCssStyleDeclaration*);
using PublicLegacyCssStyleDeclarationGetPropertyValue = AtomicStringRef (*)(LegacyCssStyleDeclaration*, const char*, SharedExceptionState*);
using PublicLegacyCssStyleDeclarationSetProperty = void (*)(LegacyCssStyleDeclaration*, const char*, NativeValue, const char*, SharedExceptionState*);
using PublicLegacyCssStyleDeclarationRemoveProperty = AtomicStringRef (*)(LegacyCssStyleDeclaration*, const char*, SharedExceptionState*);
using PublicLegacyCssStyleDeclarationRelease = void (*)(LegacyCssStyleDeclaration*);
using PublicLegacyCssStyleDeclarationDynamicTo = WebFValue<LegacyCssStyleDeclaration, WebFPublicMethods> (*)(LegacyCssStyleDeclaration*, LegacyCssStyleDeclarationType);
struct LegacyCssStyleDeclarationPublicMethods : public WebFPublicMethods {
  static AtomicStringRef CssText(LegacyCssStyleDeclaration* legacy_css_style_declaration);
  static void SetCssText(LegacyCssStyleDeclaration* legacy_css_style_declaration, const char* cssText, SharedExceptionState* shared_exception_state);
  static int64_t Length(LegacyCssStyleDeclaration* legacy_css_style_declaration);
  static AtomicStringRef GetPropertyValue(LegacyCssStyleDeclaration* legacy_css_style_declaration, const char* property, SharedExceptionState* shared_exception_state);
  static void SetProperty(LegacyCssStyleDeclaration* legacy_css_style_declaration, const char* property, NativeValue value, const char* priority, SharedExceptionState* shared_exception_state);
  static AtomicStringRef RemoveProperty(LegacyCssStyleDeclaration* legacy_css_style_declaration, const char* property, SharedExceptionState* shared_exception_state);
  static void Release(LegacyCssStyleDeclaration* legacy_css_style_declaration);
  static WebFValue<LegacyCssStyleDeclaration, WebFPublicMethods> DynamicTo(LegacyCssStyleDeclaration* legacy_css_style_declaration, LegacyCssStyleDeclarationType legacy_css_style_declaration_type);
  double version{1.0};
  PublicLegacyCssStyleDeclarationGetCssText legacy_css_style_declaration_get_css_text{CssText};
  PublicLegacyCssStyleDeclarationSetCssText legacy_css_style_declaration_set_css_text{SetCssText};
  PublicLegacyCssStyleDeclarationGetLength legacy_css_style_declaration_get_length{Length};
  PublicLegacyCssStyleDeclarationGetPropertyValue legacy_css_style_declaration_get_property_value{GetPropertyValue};
  PublicLegacyCssStyleDeclarationSetProperty legacy_css_style_declaration_set_property{SetProperty};
  PublicLegacyCssStyleDeclarationRemoveProperty legacy_css_style_declaration_remove_property{RemoveProperty};
  PublicLegacyCssStyleDeclarationRelease legacy_css_style_declaration_release{Release};
  PublicLegacyCssStyleDeclarationDynamicTo legacy_css_style_declaration_dynamic_to{DynamicTo};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_LEGACY_CSS_STYLE_DECLARATION_H_
