// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_PERFORMANCE_ENTRY_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_PERFORMANCE_ENTRY_H_
#include <stdint.h>
#include "rust_readable.h"
#include "webf_value.h"
namespace webf {
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
class PerformanceEntry;
enum class PerformanceEntryType {
  kPerformanceEntry = 0,
  kPerformanceMeasure = 1,
  kPerformanceMark = 2,
};
using PublicPerformanceEntryGetName = const char* (*)(PerformanceEntry*);
using PublicPerformanceEntryDupName = const char* (*)(PerformanceEntry*);
using PublicPerformanceEntryGetEntryType = const char* (*)(PerformanceEntry*);
using PublicPerformanceEntryDupEntryType = const char* (*)(PerformanceEntry*);
using PublicPerformanceEntryGetStartTime = int64_t (*)(PerformanceEntry*);
using PublicPerformanceEntryGetDuration = int64_t (*)(PerformanceEntry*);
using PublicPerformanceEntryToJSON = NativeValue (*)(PerformanceEntry*, SharedExceptionState*);
using PublicPerformanceEntryRelease = void (*)(PerformanceEntry*);
using PublicPerformanceEntryDynamicTo = WebFValue<PerformanceEntry, WebFPublicMethods> (*)(PerformanceEntry*, PerformanceEntryType);
struct PerformanceEntryPublicMethods : public WebFPublicMethods {
  static const char* Name(PerformanceEntry* performance_entry);
  static const char* DupName(PerformanceEntry* performance_entry);
  static const char* EntryType(PerformanceEntry* performance_entry);
  static const char* DupEntryType(PerformanceEntry* performance_entry);
  static int64_t StartTime(PerformanceEntry* performance_entry);
  static int64_t Duration(PerformanceEntry* performance_entry);
  static NativeValue ToJSON(PerformanceEntry* performance_entry, SharedExceptionState* shared_exception_state);
  static void Release(PerformanceEntry* performance_entry);
  static WebFValue<PerformanceEntry, WebFPublicMethods> DynamicTo(PerformanceEntry* performance_entry, PerformanceEntryType performance_entry_type);
  double version{1.0};
  PublicPerformanceEntryGetName performance_entry_get_name{Name};
  PublicPerformanceEntryDupName performance_entry_dup_name{DupName};
  PublicPerformanceEntryGetEntryType performance_entry_get_entry_type{EntryType};
  PublicPerformanceEntryDupEntryType performance_entry_dup_entry_type{DupEntryType};
  PublicPerformanceEntryGetStartTime performance_entry_get_start_time{StartTime};
  PublicPerformanceEntryGetDuration performance_entry_get_duration{Duration};
  PublicPerformanceEntryToJSON performance_entry_to_json{ToJSON};
  PublicPerformanceEntryRelease performance_entry_release{Release};
  PublicPerformanceEntryDynamicTo performance_entry_dynamic_to{DynamicTo};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_PERFORMANCE_ENTRY_H_
