// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_TOUCH_EVENT_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_TOUCH_EVENT_H_
#include <stdint.h>
#include "core/native/vector_value_ref.h"
#include "rust_readable.h"
#include "ui_event.h"
namespace webf {
class TouchList;
typedef struct TouchListPublicMethods TouchListPublicMethods;
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
typedef struct AtomicStringRef AtomicStringRef;
class TouchEvent;
using PublicTouchEventGetTouches = WebFValue<webf::TouchList, TouchListPublicMethods> (*)(TouchEvent*);
using PublicTouchEventGetTargetTouches = WebFValue<webf::TouchList, TouchListPublicMethods> (*)(TouchEvent*);
using PublicTouchEventGetChangedTouches = WebFValue<webf::TouchList, TouchListPublicMethods> (*)(TouchEvent*);
using PublicTouchEventGetAltKey = int32_t (*)(TouchEvent*);
using PublicTouchEventGetMetaKey = int32_t (*)(TouchEvent*);
using PublicTouchEventGetCtrlKey = int32_t (*)(TouchEvent*);
using PublicTouchEventGetShiftKey = int32_t (*)(TouchEvent*);
struct TouchEventPublicMethods : public WebFPublicMethods {
  static WebFValue<webf::TouchList, TouchListPublicMethods> Touches(TouchEvent* touch_event);
  static WebFValue<webf::TouchList, TouchListPublicMethods> TargetTouches(TouchEvent* touch_event);
  static WebFValue<webf::TouchList, TouchListPublicMethods> ChangedTouches(TouchEvent* touch_event);
  static int32_t AltKey(TouchEvent* touch_event);
  static int32_t MetaKey(TouchEvent* touch_event);
  static int32_t CtrlKey(TouchEvent* touch_event);
  static int32_t ShiftKey(TouchEvent* touch_event);
  double version{1.0};
  UIEventPublicMethods ui_event;
  PublicTouchEventGetTouches touch_event_get_touches{Touches};
  PublicTouchEventGetTargetTouches touch_event_get_target_touches{TargetTouches};
  PublicTouchEventGetChangedTouches touch_event_get_changed_touches{ChangedTouches};
  PublicTouchEventGetAltKey touch_event_get_alt_key{AltKey};
  PublicTouchEventGetMetaKey touch_event_get_meta_key{MetaKey};
  PublicTouchEventGetCtrlKey touch_event_get_ctrl_key{CtrlKey};
  PublicTouchEventGetShiftKey touch_event_get_shift_key{ShiftKey};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_TOUCH_EVENT_H_
