// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
// clang-format off
/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */
#ifndef WEBF_CORE_WEBF_API_PLUGIN_API_TOUCH_LIST_H_
#define WEBF_CORE_WEBF_API_PLUGIN_API_TOUCH_LIST_H_
#include <stdint.h>
#include "core/native/vector_value_ref.h"
#include "rust_readable.h"
#include "webf_value.h"
namespace webf {
class Touch;
typedef struct TouchPublicMethods TouchPublicMethods;
class SharedExceptionState;
class ExecutingContext;
typedef struct NativeValue NativeValue;
typedef struct AtomicStringRef AtomicStringRef;
class TouchList;
enum class TouchListType {
  kTouchList = 0,
};
using PublicTouchListGetLength = double (*)(TouchList*);
using PublicTouchListItem = WebFValue<Touch, TouchPublicMethods> (*)(TouchList*, double, SharedExceptionState*);
using PublicTouchListRelease = void (*)(TouchList*);
using PublicTouchListDynamicTo = WebFValue<TouchList, WebFPublicMethods> (*)(TouchList*, TouchListType);
struct TouchListPublicMethods : public WebFPublicMethods {
  static double Length(TouchList* touch_list);
  static WebFValue<Touch, TouchPublicMethods> Item(TouchList* touch_list, double index, SharedExceptionState* shared_exception_state);
  static void Release(TouchList* touch_list);
  static WebFValue<TouchList, WebFPublicMethods> DynamicTo(TouchList* touch_list, TouchListType touch_list_type);
  double version{1.0};
  PublicTouchListGetLength touch_list_get_length{Length};
  PublicTouchListItem touch_list_item{Item};
  PublicTouchListRelease touch_list_release{Release};
  PublicTouchListDynamicTo touch_list_dynamic_to{DynamicTo};
};
}  // namespace webf
#endif  // WEBF_CORE_WEBF_API_PLUGIN_API_TOUCH_LIST_H_
