// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen generate --flutter-package-src=./webf/lib/src/cupertino --framework=<framework> <distPath>
import 'package:webf/webf.dart';
abstract class FlutterCupertinoInputBindings extends WidgetElement {
  FlutterCupertinoInputBindings(super.context);
  String? get val;
  set val(value);
  String? get placeholder;
  set placeholder(value);
  String? get type;
  set type(value);
  bool? get disabled;
  set disabled(value);
  bool get autofocus;
  set autofocus(value);
  bool? get clearable;
  set clearable(value);
  int? get maxlength;
  set maxlength(value);
  bool? get readonly;
  set readonly(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['val'] = ElementAttributeProperty(
      getter: () => val.toString(),
      setter: (value) => val = value
    );
    attributes['placeholder'] = ElementAttributeProperty(
      getter: () => placeholder.toString(),
      setter: (value) => placeholder = value
    );
    attributes['type'] = ElementAttributeProperty(
      getter: () => type.toString(),
      setter: (value) => type = value
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => disabled = value
    );
    attributes['autofocus'] = ElementAttributeProperty(
      getter: () => autofocus.toString(),
      setter: (value) => autofocus = value
    );
    attributes['clearable'] = ElementAttributeProperty(
      getter: () => clearable.toString(),
      setter: (value) => clearable = value
    );
    attributes['maxlength'] = ElementAttributeProperty(
      getter: () => maxlength.toString(),
      setter: (value) => maxlength = value
    );
    attributes['readonly'] = ElementAttributeProperty(
      getter: () => readonly.toString(),
      setter: (value) => readonly = value
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoInputProperties = {
    'val': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).val,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).val = value,
    ),
    'placeholder': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).placeholder,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).placeholder = value,
    ),
    'type': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).type,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).type = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).disabled = value,
    ),
    'autofocus': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).autofocus,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).autofocus = value,
    ),
    'clearable': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).clearable,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).clearable = value,
    ),
    'maxlength': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).maxlength,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).maxlength = value,
    ),
    'readonly': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoInputBindings>(element).readonly,
      setter: (element, value) =>
      castToType<FlutterCupertinoInputBindings>(element).readonly = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoInputProperties,
  ];
  String getValue(List<dynamic> args);
  void setValue(List<dynamic> args);
  void focus(List<dynamic> args);
  void blur(List<dynamic> args);
  static StaticDefinedSyncBindingObjectMethodMap flutterCupertinoInputMethods = {
    'getValue': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoInputBindings>(element).getValue(args);
      },
    ),
    'setValue': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoInputBindings>(element).setValue(args);
      },
    ),
    'focus': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoInputBindings>(element).focus(args);
      },
    ),
    'blur': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoInputBindings>(element).blur(args);
      },
    ),
  };
  @override
  List<StaticDefinedSyncBindingObjectMethodMap> get methods => [
    ...super.methods,
    flutterCupertinoInputMethods,
  ];
}