// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen generate --flutter-package-src=./webf/lib/src/cupertino --framework=<framework> <distPath>
import 'package:webf/webf.dart';
abstract class FlutterCupertinoModalPopupBindings extends WidgetElement {
  FlutterCupertinoModalPopupBindings(super.context);
  bool? get visible;
  set visible(value);
  int? get height;
  set height(value);
  bool? get surfacePainted;
  set surfacePainted(value);
  bool? get maskClosable;
  set maskClosable(value);
  double? get backgroundOpacity;
  set backgroundOpacity(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['visible'] = ElementAttributeProperty(
      getter: () => visible.toString(),
      setter: (value) => visible = value
    );
    attributes['height'] = ElementAttributeProperty(
      getter: () => height.toString(),
      setter: (value) => height = value
    );
    attributes['surface-painted'] = ElementAttributeProperty(
      getter: () => surfacePainted.toString(),
      setter: (value) => surfacePainted = value
    );
    attributes['mask-closable'] = ElementAttributeProperty(
      getter: () => maskClosable.toString(),
      setter: (value) => maskClosable = value
    );
    attributes['background-opacity'] = ElementAttributeProperty(
      getter: () => backgroundOpacity.toString(),
      setter: (value) => backgroundOpacity = value
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoModalPopupProperties = {
    'visible': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoModalPopupBindings>(element).visible,
      setter: (element, value) =>
      castToType<FlutterCupertinoModalPopupBindings>(element).visible = value,
    ),
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoModalPopupBindings>(element).height,
      setter: (element, value) =>
      castToType<FlutterCupertinoModalPopupBindings>(element).height = value,
    ),
    'surfacePainted': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoModalPopupBindings>(element).surfacePainted,
      setter: (element, value) =>
      castToType<FlutterCupertinoModalPopupBindings>(element).surfacePainted = value,
    ),
    'maskClosable': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoModalPopupBindings>(element).maskClosable,
      setter: (element, value) =>
      castToType<FlutterCupertinoModalPopupBindings>(element).maskClosable = value,
    ),
    'backgroundOpacity': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoModalPopupBindings>(element).backgroundOpacity,
      setter: (element, value) =>
      castToType<FlutterCupertinoModalPopupBindings>(element).backgroundOpacity = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoModalPopupProperties,
  ];
  void show(List<dynamic> args);
  void hide(List<dynamic> args);
  static StaticDefinedSyncBindingObjectMethodMap flutterCupertinoModalPopupMethods = {
    'show': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoModalPopupBindings>(element).show(args);
      },
    ),
    'hide': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoModalPopupBindings>(element).hide(args);
      },
    ),
  };
  @override
  List<StaticDefinedSyncBindingObjectMethodMap> get methods => [
    ...super.methods,
    flutterCupertinoModalPopupMethods,
  ];
}