// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen generate --flutter-package-src=./webf/lib/src/cupertino --framework=<framework> <distPath>
import 'package:webf/webf.dart';
abstract class FlutterCupertinoSearchInputBindings extends WidgetElement {
  FlutterCupertinoSearchInputBindings(super.context);
  String? get val;
  set val(value);
  String? get placeholder;
  set placeholder(value);
  bool? get disabled;
  set disabled(value);
  String? get type;
  set type(value);
  String? get prefixIcon;
  set prefixIcon(value);
  String? get suffixIcon;
  set suffixIcon(value);
  String? get suffixModel;
  set suffixModel(value);
  String? get itemColor;
  set itemColor(value);
  double? get itemSize;
  set itemSize(value);
  bool get autofocus;
  set autofocus(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['val'] = ElementAttributeProperty(
      getter: () => val.toString(),
      setter: (value) => val = value
    );
    attributes['placeholder'] = ElementAttributeProperty(
      getter: () => placeholder.toString(),
      setter: (value) => placeholder = value
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => disabled = value
    );
    attributes['type'] = ElementAttributeProperty(
      getter: () => type.toString(),
      setter: (value) => type = value
    );
    attributes['prefix-icon'] = ElementAttributeProperty(
      getter: () => prefixIcon.toString(),
      setter: (value) => prefixIcon = value
    );
    attributes['suffix-icon'] = ElementAttributeProperty(
      getter: () => suffixIcon.toString(),
      setter: (value) => suffixIcon = value
    );
    attributes['suffix-model'] = ElementAttributeProperty(
      getter: () => suffixModel.toString(),
      setter: (value) => suffixModel = value
    );
    attributes['item-color'] = ElementAttributeProperty(
      getter: () => itemColor.toString(),
      setter: (value) => itemColor = value
    );
    attributes['item-size'] = ElementAttributeProperty(
      getter: () => itemSize.toString(),
      setter: (value) => itemSize = value
    );
    attributes['autofocus'] = ElementAttributeProperty(
      getter: () => autofocus.toString(),
      setter: (value) => autofocus = value
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoSearchInputProperties = {
    'val': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).val,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).val = value,
    ),
    'placeholder': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).placeholder,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).placeholder = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).disabled = value,
    ),
    'type': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).type,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).type = value,
    ),
    'prefixIcon': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).prefixIcon,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).prefixIcon = value,
    ),
    'suffixIcon': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).suffixIcon,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).suffixIcon = value,
    ),
    'suffixModel': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).suffixModel,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).suffixModel = value,
    ),
    'itemColor': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).itemColor,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).itemColor = value,
    ),
    'itemSize': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).itemSize,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).itemSize = value,
    ),
    'autofocus': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).autofocus,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).autofocus = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoSearchInputProperties,
  ];
  String getValue(List<dynamic> args);
  void setValue(List<dynamic> args);
  void focus(List<dynamic> args);
  void blur(List<dynamic> args);
  void clear(List<dynamic> args);
  static StaticDefinedSyncBindingObjectMethodMap flutterCupertinoSearchInputMethods = {
    'getValue': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoSearchInputBindings>(element).getValue(args);
      },
    ),
    'setValue': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoSearchInputBindings>(element).setValue(args);
      },
    ),
    'focus': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoSearchInputBindings>(element).focus(args);
      },
    ),
    'blur': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoSearchInputBindings>(element).blur(args);
      },
    ),
    'clear': StaticDefinedSyncBindingObjectMethod(
      call: (element, args) {
        return castToType<FlutterCupertinoSearchInputBindings>(element).clear(args);
      },
    ),
  };
  @override
  List<StaticDefinedSyncBindingObjectMethodMap> get methods => [
    ...super.methods,
    flutterCupertinoSearchInputMethods,
  ];
}