// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf module-codegen`

import 'package:webf/module.dart';
import 'package:webf/dom.dart';

class AdapterStateResult {
  final String success;
  final String? state;
  final String? error;

  const AdapterStateResult({required this.success, this.state, this.error});

  factory AdapterStateResult.fromMap(Map<String, dynamic> map) {
    return AdapterStateResult(
      success: map['success']?.toString() ?? '',
      state: map['state']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (state != null) { map['state'] = state; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class IsBluetoothOnResult {
  final String success;
  final String? isOn;
  final String? error;

  const IsBluetoothOnResult({required this.success, this.isOn, this.error});

  factory IsBluetoothOnResult.fromMap(Map<String, dynamic> map) {
    return IsBluetoothOnResult(
      success: map['success']?.toString() ?? '',
      isOn: map['isOn']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (isOn != null) { map['isOn'] = isOn; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class TurnOnResult {
  final String success;
  final String? error;

  const TurnOnResult({required this.success, this.error});

  factory TurnOnResult.fromMap(Map<String, dynamic> map) {
    return TurnOnResult(
      success: map['success']?.toString() ?? '',
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ScanOptions {
  final dynamic serviceUuids;
  final num? timeout;
  final bool? allowDuplicates;
  final num? androidScanMode;

  const ScanOptions({this.serviceUuids, this.timeout, this.allowDuplicates, this.androidScanMode});

  factory ScanOptions.fromMap(Map<String, dynamic> map) {
    return ScanOptions(
      serviceUuids: map['serviceUuids'],
      timeout: map['timeout'] is num ? map['timeout'] as num : null,
      allowDuplicates: map['allowDuplicates'] is bool ? map['allowDuplicates'] as bool : null,
      androidScanMode: map['androidScanMode'] is num ? map['androidScanMode'] as num : null,
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    if (serviceUuids != null) { map['serviceUuids'] = serviceUuids; }
    if (timeout != null) { map['timeout'] = timeout; }
    if (allowDuplicates != null) { map['allowDuplicates'] = allowDuplicates; }
    if (androidScanMode != null) { map['androidScanMode'] = androidScanMode; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ScanStartResult {
  final String success;
  final String? scanId;
  final String? error;

  const ScanStartResult({required this.success, this.scanId, this.error});

  factory ScanStartResult.fromMap(Map<String, dynamic> map) {
    return ScanStartResult(
      success: map['success']?.toString() ?? '',
      scanId: map['scanId']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (scanId != null) { map['scanId'] = scanId; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ScanStopResult {
  final String success;
  final String? error;

  const ScanStopResult({required this.success, this.error});

  factory ScanStopResult.fromMap(Map<String, dynamic> map) {
    return ScanStopResult(
      success: map['success']?.toString() ?? '',
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class IsScanningResult {
  final String success;
  final String? isScanning;
  final String? error;

  const IsScanningResult({required this.success, this.isScanning, this.error});

  factory IsScanningResult.fromMap(Map<String, dynamic> map) {
    return IsScanningResult(
      success: map['success']?.toString() ?? '',
      isScanning: map['isScanning']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (isScanning != null) { map['isScanning'] = isScanning; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ConnectOptions {
  final String deviceId;
  final num? timeout;
  final bool? autoConnect;
  final num? mtu;

  const ConnectOptions({required this.deviceId, this.timeout, this.autoConnect, this.mtu});

  factory ConnectOptions.fromMap(Map<String, dynamic> map) {
    return ConnectOptions(
      deviceId: map['deviceId']?.toString() ?? '',
      timeout: map['timeout'] is num ? map['timeout'] as num : null,
      autoConnect: map['autoConnect'] is bool ? map['autoConnect'] as bool : null,
      mtu: map['mtu'] is num ? map['mtu'] as num : null,
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    if (timeout != null) { map['timeout'] = timeout; }
    if (autoConnect != null) { map['autoConnect'] = autoConnect; }
    if (mtu != null) { map['mtu'] = mtu; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ConnectResult {
  final String success;
  final String? connectionId;
  final num? mtu;
  final String? error;

  const ConnectResult({required this.success, this.connectionId, this.mtu, this.error});

  factory ConnectResult.fromMap(Map<String, dynamic> map) {
    return ConnectResult(
      success: map['success']?.toString() ?? '',
      connectionId: map['connectionId']?.toString(),
      mtu: map['mtu'] is num ? map['mtu'] as num : null,
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (connectionId != null) { map['connectionId'] = connectionId; }
    if (mtu != null) { map['mtu'] = mtu; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class DisconnectResult {
  final String success;
  final String? error;

  const DisconnectResult({required this.success, this.error});

  factory DisconnectResult.fromMap(Map<String, dynamic> map) {
    return DisconnectResult(
      success: map['success']?.toString() ?? '',
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ConnectionStateResult {
  final String success;
  final String? state;
  final String? error;

  const ConnectionStateResult({required this.success, this.state, this.error});

  factory ConnectionStateResult.fromMap(Map<String, dynamic> map) {
    return ConnectionStateResult(
      success: map['success']?.toString() ?? '',
      state: map['state']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (state != null) { map['state'] = state; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ConnectedDevicesResult {
  final String success;
  final String? devices;
  final String? error;

  const ConnectedDevicesResult({required this.success, this.devices, this.error});

  factory ConnectedDevicesResult.fromMap(Map<String, dynamic> map) {
    return ConnectedDevicesResult(
      success: map['success']?.toString() ?? '',
      devices: map['devices']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (devices != null) { map['devices'] = devices; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class RequestMtuResult {
  final String success;
  final num? mtu;
  final String? error;

  const RequestMtuResult({required this.success, this.mtu, this.error});

  factory RequestMtuResult.fromMap(Map<String, dynamic> map) {
    return RequestMtuResult(
      success: map['success']?.toString() ?? '',
      mtu: map['mtu'] is num ? map['mtu'] as num : null,
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (mtu != null) { map['mtu'] = mtu; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class DiscoverServicesResult {
  final String success;
  final String? services;
  final String? error;

  const DiscoverServicesResult({required this.success, this.services, this.error});

  factory DiscoverServicesResult.fromMap(Map<String, dynamic> map) {
    return DiscoverServicesResult(
      success: map['success']?.toString() ?? '',
      services: map['services']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (services != null) { map['services'] = services; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ReadCharacteristicOptions {
  final String deviceId;
  final String serviceUuid;
  final String characteristicUuid;

  const ReadCharacteristicOptions({required this.deviceId, required this.serviceUuid, required this.characteristicUuid});

  factory ReadCharacteristicOptions.fromMap(Map<String, dynamic> map) {
    return ReadCharacteristicOptions(
      deviceId: map['deviceId']?.toString() ?? '',
      serviceUuid: map['serviceUuid']?.toString() ?? '',
      characteristicUuid: map['characteristicUuid']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    map['serviceUuid'] = serviceUuid;
    map['characteristicUuid'] = characteristicUuid;
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ReadCharacteristicResult {
  final String success;
  final String? value;
  final String? valueBase64;
  final String? error;

  const ReadCharacteristicResult({required this.success, this.value, this.valueBase64, this.error});

  factory ReadCharacteristicResult.fromMap(Map<String, dynamic> map) {
    return ReadCharacteristicResult(
      success: map['success']?.toString() ?? '',
      value: map['value']?.toString(),
      valueBase64: map['valueBase64']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (value != null) { map['value'] = value; }
    if (valueBase64 != null) { map['valueBase64'] = valueBase64; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class WriteCharacteristicOptions {
  final String deviceId;
  final String serviceUuid;
  final String characteristicUuid;
  final String? value;
  final String? valueBase64;
  final bool? withoutResponse;

  const WriteCharacteristicOptions({required this.deviceId, required this.serviceUuid, required this.characteristicUuid, this.value, this.valueBase64, this.withoutResponse});

  factory WriteCharacteristicOptions.fromMap(Map<String, dynamic> map) {
    return WriteCharacteristicOptions(
      deviceId: map['deviceId']?.toString() ?? '',
      serviceUuid: map['serviceUuid']?.toString() ?? '',
      characteristicUuid: map['characteristicUuid']?.toString() ?? '',
      value: map['value']?.toString(),
      valueBase64: map['valueBase64']?.toString(),
      withoutResponse: map['withoutResponse'] is bool ? map['withoutResponse'] as bool : null,
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    map['serviceUuid'] = serviceUuid;
    map['characteristicUuid'] = characteristicUuid;
    if (value != null) { map['value'] = value; }
    if (valueBase64 != null) { map['valueBase64'] = valueBase64; }
    if (withoutResponse != null) { map['withoutResponse'] = withoutResponse; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class WriteCharacteristicResult {
  final String success;
  final String? error;

  const WriteCharacteristicResult({required this.success, this.error});

  factory WriteCharacteristicResult.fromMap(Map<String, dynamic> map) {
    return WriteCharacteristicResult(
      success: map['success']?.toString() ?? '',
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ReadDescriptorOptions {
  final String deviceId;
  final String serviceUuid;
  final String characteristicUuid;
  final String descriptorUuid;

  const ReadDescriptorOptions({required this.deviceId, required this.serviceUuid, required this.characteristicUuid, required this.descriptorUuid});

  factory ReadDescriptorOptions.fromMap(Map<String, dynamic> map) {
    return ReadDescriptorOptions(
      deviceId: map['deviceId']?.toString() ?? '',
      serviceUuid: map['serviceUuid']?.toString() ?? '',
      characteristicUuid: map['characteristicUuid']?.toString() ?? '',
      descriptorUuid: map['descriptorUuid']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    map['serviceUuid'] = serviceUuid;
    map['characteristicUuid'] = characteristicUuid;
    map['descriptorUuid'] = descriptorUuid;
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class ReadDescriptorResult {
  final String success;
  final String? value;
  final String? valueBase64;
  final String? error;

  const ReadDescriptorResult({required this.success, this.value, this.valueBase64, this.error});

  factory ReadDescriptorResult.fromMap(Map<String, dynamic> map) {
    return ReadDescriptorResult(
      success: map['success']?.toString() ?? '',
      value: map['value']?.toString(),
      valueBase64: map['valueBase64']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (value != null) { map['value'] = value; }
    if (valueBase64 != null) { map['valueBase64'] = valueBase64; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class WriteDescriptorOptions {
  final String deviceId;
  final String serviceUuid;
  final String characteristicUuid;
  final String descriptorUuid;
  final String? value;
  final String? valueBase64;

  const WriteDescriptorOptions({required this.deviceId, required this.serviceUuid, required this.characteristicUuid, required this.descriptorUuid, this.value, this.valueBase64});

  factory WriteDescriptorOptions.fromMap(Map<String, dynamic> map) {
    return WriteDescriptorOptions(
      deviceId: map['deviceId']?.toString() ?? '',
      serviceUuid: map['serviceUuid']?.toString() ?? '',
      characteristicUuid: map['characteristicUuid']?.toString() ?? '',
      descriptorUuid: map['descriptorUuid']?.toString() ?? '',
      value: map['value']?.toString(),
      valueBase64: map['valueBase64']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    map['serviceUuid'] = serviceUuid;
    map['characteristicUuid'] = characteristicUuid;
    map['descriptorUuid'] = descriptorUuid;
    if (value != null) { map['value'] = value; }
    if (valueBase64 != null) { map['valueBase64'] = valueBase64; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class WriteDescriptorResult {
  final String success;
  final String? error;

  const WriteDescriptorResult({required this.success, this.error});

  factory WriteDescriptorResult.fromMap(Map<String, dynamic> map) {
    return WriteDescriptorResult(
      success: map['success']?.toString() ?? '',
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class SubscribeOptions {
  final String deviceId;
  final String serviceUuid;
  final String characteristicUuid;

  const SubscribeOptions({required this.deviceId, required this.serviceUuid, required this.characteristicUuid});

  factory SubscribeOptions.fromMap(Map<String, dynamic> map) {
    return SubscribeOptions(
      deviceId: map['deviceId']?.toString() ?? '',
      serviceUuid: map['serviceUuid']?.toString() ?? '',
      characteristicUuid: map['characteristicUuid']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    map['serviceUuid'] = serviceUuid;
    map['characteristicUuid'] = characteristicUuid;
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class SubscribeResult {
  final String success;
  final String? subscriptionId;
  final String? error;

  const SubscribeResult({required this.success, this.subscriptionId, this.error});

  factory SubscribeResult.fromMap(Map<String, dynamic> map) {
    return SubscribeResult(
      success: map['success']?.toString() ?? '',
      subscriptionId: map['subscriptionId']?.toString(),
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (subscriptionId != null) { map['subscriptionId'] = subscriptionId; }
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class UnsubscribeResult {
  final String success;
  final String? error;

  const UnsubscribeResult({required this.success, this.error});

  factory UnsubscribeResult.fromMap(Map<String, dynamic> map) {
    return UnsubscribeResult(
      success: map['success']?.toString() ?? '',
      error: map['error']?.toString(),
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['success'] = success;
    if (error != null) { map['error'] = error; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class BluetoothScanResultPayload {
  final String deviceId;
  final String remoteId;
  final String? name;
  final String? localName;
  final num rssi;
  final dynamic serviceUuids;
  final String? manufacturerData;
  final bool connectable;
  final num? txPowerLevel;

  const BluetoothScanResultPayload({required this.deviceId, required this.remoteId, this.name, this.localName, required this.rssi, this.serviceUuids, this.manufacturerData, required this.connectable, this.txPowerLevel});

  factory BluetoothScanResultPayload.fromMap(Map<String, dynamic> map) {
    return BluetoothScanResultPayload(
      deviceId: map['deviceId']?.toString() ?? '',
      remoteId: map['remoteId']?.toString() ?? '',
      name: map['name']?.toString(),
      localName: map['localName']?.toString(),
      rssi: map['rssi'] is num ? map['rssi'] as num : 0,
      serviceUuids: map['serviceUuids'],
      manufacturerData: map['manufacturerData']?.toString(),
      connectable: map['connectable'] is bool ? map['connectable'] as bool : false,
      txPowerLevel: map['txPowerLevel'] is num ? map['txPowerLevel'] as num : null,
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    map['remoteId'] = remoteId;
    if (name != null) { map['name'] = name; }
    if (localName != null) { map['localName'] = localName; }
    map['rssi'] = rssi;
    if (serviceUuids != null) { map['serviceUuids'] = serviceUuids; }
    if (manufacturerData != null) { map['manufacturerData'] = manufacturerData; }
    map['connectable'] = connectable;
    if (txPowerLevel != null) { map['txPowerLevel'] = txPowerLevel; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class BluetoothConnectionStatePayload {
  final String deviceId;
  final dynamic state;

  const BluetoothConnectionStatePayload({required this.deviceId, this.state});

  factory BluetoothConnectionStatePayload.fromMap(Map<String, dynamic> map) {
    return BluetoothConnectionStatePayload(
      deviceId: map['deviceId']?.toString() ?? '',
      state: map['state'],
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['deviceId'] = deviceId;
    if (state != null) { map['state'] = state; }
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

class BluetoothNotificationPayload {
  final String subscriptionId;
  final String deviceId;
  final String serviceUuid;
  final String characteristicUuid;
  final String value;
  final String valueBase64;

  const BluetoothNotificationPayload({required this.subscriptionId, required this.deviceId, required this.serviceUuid, required this.characteristicUuid, required this.value, required this.valueBase64});

  factory BluetoothNotificationPayload.fromMap(Map<String, dynamic> map) {
    return BluetoothNotificationPayload(
      subscriptionId: map['subscriptionId']?.toString() ?? '',
      deviceId: map['deviceId']?.toString() ?? '',
      serviceUuid: map['serviceUuid']?.toString() ?? '',
      characteristicUuid: map['characteristicUuid']?.toString() ?? '',
      value: map['value']?.toString() ?? '',
      valueBase64: map['valueBase64']?.toString() ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{};
    map['subscriptionId'] = subscriptionId;
    map['deviceId'] = deviceId;
    map['serviceUuid'] = serviceUuid;
    map['characteristicUuid'] = characteristicUuid;
    map['value'] = value;
    map['valueBase64'] = valueBase64;
    return map;
  }

  Map<String, dynamic> toJson() => toMap();
}

abstract class BluetoothModuleBindings extends WebFBaseModule {
  BluetoothModuleBindings(super.moduleManager);

  @override
  String get name => 'Bluetooth';

  dynamic emitScanResult({Event? event, BluetoothScanResultPayload? data}) {
    final mapped = data?.toMap();
    return dispatchEvent(event: event ?? Event('scanResult'), data: mapped);
  }

  dynamic emitConnectionState({Event? event, BluetoothConnectionStatePayload? data}) {
    final mapped = data?.toMap();
    return dispatchEvent(event: event ?? Event('connectionState'), data: mapped);
  }

  dynamic emitNotification({Event? event, BluetoothNotificationPayload? data}) {
    final mapped = data?.toMap();
    return dispatchEvent(event: event ?? Event('notification'), data: mapped);
  }

  Future<AdapterStateResult> getAdapterState();
  Future<IsBluetoothOnResult> isBluetoothOn();
  Future<TurnOnResult> turnOn();
  Future<ScanStartResult> startScan(ScanOptions? options);
  Future<ScanStopResult> stopScan();
  Future<IsScanningResult> isScanning();
  Future<ConnectResult> connect(ConnectOptions? options);
  Future<DisconnectResult> disconnect(dynamic deviceId);
  Future<ConnectionStateResult> getConnectionState(dynamic deviceId);
  Future<ConnectedDevicesResult> getConnectedDevices();
  Future<RequestMtuResult> requestMtu(dynamic deviceId, dynamic mtu);
  Future<DiscoverServicesResult> discoverServices(dynamic deviceId);
  Future<ReadCharacteristicResult> readCharacteristic(ReadCharacteristicOptions? options);
  Future<WriteCharacteristicResult> writeCharacteristic(WriteCharacteristicOptions? options);
  Future<ReadDescriptorResult> readDescriptor(ReadDescriptorOptions? options);
  Future<WriteDescriptorResult> writeDescriptor(WriteDescriptorOptions? options);
  Future<SubscribeResult> subscribeToNotifications(SubscribeOptions? options);
  Future<UnsubscribeResult> unsubscribeFromNotifications(dynamic subscriptionId);

  @override
  Future<dynamic> invoke(String method, List<dynamic> params) async {
    switch (method) {
      case 'getAdapterState': {
        final result = await getAdapterState();
        return result.toMap();
      }
      case 'isBluetoothOn': {
        final result = await isBluetoothOn();
        return result.toMap();
      }
      case 'turnOn': {
        final result = await turnOn();
        return result.toMap();
      }
      case 'startScan': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? ScanOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as ScanOptions?);
        final result = await startScan(options);
        return result.toMap();
      }
      case 'stopScan': {
        final result = await stopScan();
        return result.toMap();
      }
      case 'isScanning': {
        final result = await isScanning();
        return result.toMap();
      }
      case 'connect': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? ConnectOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as ConnectOptions?);
        final result = await connect(options);
        return result.toMap();
      }
      case 'disconnect': {
        final result = await disconnect(params.length > 0 ? params[0] : null);
        return result.toMap();
      }
      case 'getConnectionState': {
        final result = await getConnectionState(params.length > 0 ? params[0] : null);
        return result.toMap();
      }
      case 'getConnectedDevices': {
        final result = await getConnectedDevices();
        return result.toMap();
      }
      case 'requestMtu': {
        final result = await requestMtu(params.length > 0 ? params[0] : null, params.length > 1 ? params[1] : null);
        return result.toMap();
      }
      case 'discoverServices': {
        final result = await discoverServices(params.length > 0 ? params[0] : null);
        return result.toMap();
      }
      case 'readCharacteristic': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? ReadCharacteristicOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as ReadCharacteristicOptions?);
        final result = await readCharacteristic(options);
        return result.toMap();
      }
      case 'writeCharacteristic': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? WriteCharacteristicOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as WriteCharacteristicOptions?);
        final result = await writeCharacteristic(options);
        return result.toMap();
      }
      case 'readDescriptor': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? ReadDescriptorOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as ReadDescriptorOptions?);
        final result = await readDescriptor(options);
        return result.toMap();
      }
      case 'writeDescriptor': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? WriteDescriptorOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as WriteDescriptorOptions?);
        final result = await writeDescriptor(options);
        return result.toMap();
      }
      case 'subscribeToNotifications': {
        final _raw0 = params.length > 0 ? params[0] : null;
        final options = _raw0 is Map ? SubscribeOptions.fromMap(Map<String, dynamic>.from(_raw0 as Map)) : (_raw0 as SubscribeOptions?);
        final result = await subscribeToNotifications(options);
        return result.toMap();
      }
      case 'unsubscribeFromNotifications': {
        final result = await unsubscribeFromNotifications(params.length > 0 ? params[0] : null);
        return result.toMap();
      }
      default:
        throw Exception('Unknown method for module ${name}: $method');
    }
  }
}
