/*
 * Copyright (C) 2024-present The OpenWebF Company. All rights reserved.
 * Licensed under GNU GPL with Enterprise exception.
 */
import fs from 'fs';
import path from 'path';
import JSON5 from 'json5';
import { CSSProperties } from './css_properties';

function escapeDartString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function toStylePropertyName(propertyName: string): string {
  // Keep custom properties intact.
  if (propertyName.length >= 2 && propertyName[0] === '-' && propertyName[1] === '-') {
    return propertyName;
  }

  if (!propertyName.includes('-')) {
    return propertyName;
  }

  let result = '';
  let upperNext = false;
  for (const ch of propertyName) {
    if (ch === '-') {
      upperNext = true;
      continue;
    }
    if (upperNext) {
      result += ch.toUpperCase();
      upperNext = false;
    } else {
      result += ch;
    }
  }
  return result;
}

function formatDartStringList(items: string[], indent = '  '): string {
  return items.map((item) => `${indent}'${escapeDartString(item)}',`).join('\n');
}

export function makeDartBlinkCssIds() {
  const properties = new CSSProperties();
  const maxPropertyId = properties.last_unresolved_property_id;

  const propertyNameById: string[] = Array.from({ length: maxPropertyId + 1 }, () => '');
  // kInvalid = 0, kVariable = 1 (custom properties need a string key).
  propertyNameById[0] = '';
  propertyNameById[1] = '';

  for (const prop of properties.properties_including_aliases) {
    const id = prop.enum_value!;
    propertyNameById[id] = toStylePropertyName(prop.name);
  }

  const cssValueKeywordsPath = path.join(__dirname, '../../../../core/css/css_value_keywords.json5');
  const cssValueKeywords = JSON5.parse(fs.readFileSync(cssValueKeywordsPath, { encoding: 'utf-8' }));
  const keywords: string[] = cssValueKeywords.data ?? [];

  const valueKeywordById: string[] = [''];
  for (const keyword of keywords) {
    valueKeywordById.push(keyword);
  }

  const source = [
    '// This file is auto-generated by WebF JSON code generator.',
    '// DO NOT EDIT - Any changes will be overwritten during the next build.',
    '//',
    '// Generated by: bridge/scripts/code_generator/src/json/make_dart_blink_css_ids.ts',
    '// From JSON5 files:',
    '// - bridge/core/css/css_properties.json5',
    '// - bridge/core/css/css_value_keywords.json5',
    '',
    '/// Index: native (Blink) CSSPropertyID integer value.',
    '/// Value: JS/CSSOM style property name expected by the Dart style engine (camelCase; vendor-prefixed may start with an uppercase letter).',
    'const List<String> blinkCSSPropertyIdToStyleName = <String>[',
    formatDartStringList(propertyNameById),
    '];',
    '',
    '/// Index: native (Blink) CSSValueID integer value.',
    "/// Value: CSS keyword string (e.g. 'none', 'block').",
    'const List<String> blinkCSSValueIdToKeyword = <String>[',
    formatDartStringList(valueKeywordById),
    '];',
    '',
  ].join('\n');

  return { source };
}
