<%
const lprefix = options.prefix.toLowerCase()
const uprefix = options.prefix.toUpperCase()
%>
/*
* This file is auto-generated by WebF JSON code generator from JSON5 definitions.
* DO NOT EDIT - Any changes will be overwritten during the next build.
* 
* Generated by: bridge/scripts/code_generator/src/json/generator.ts
* From JSON5 file: bridge/core/html/<%= lprefix %>_element_factory.json5
*
* Copyright (C) 2019-2022 The Kraken authors. All rights reserved.
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/

#ifndef BRIDGE_CORE_<%=uprefix%>_ELEMENT_FACTORY_H_
#define BRIDGE_CORE_<%=uprefix%>_ELEMENT_FACTORY_H_

#include "foundation/string/atomic_string.h"

namespace webf {

class Document;
class <%=uprefix%>Element;

class <%=uprefix%>ElementFactory {
 public:
  // If |local_name| is unknown, nullptr is returned.
  static <%=uprefix%>Element* Create(const AtomicString& local_name, Document&);
  static void Dispose();
};

}  // namespace webf

#endif  // BRIDGE_CORE_<%=uprefix%>_ELEMENT_FACTORY_H_
