/*
 * Generated by TSDL, don't edit this file directly.
 */

<% if (events) { %>
import React, { EventHandler, SyntheticEvent } from "react";
<% } %>
import { createComponent } from "<%= utilsPath %>";

<%= dependencies %>

interface <%= className %>Props {
  <% _.forEach(properties?.props, function(prop, index) { %>
    <% var propName = _.camelCase(prop.name); %>
    <% if (prop.optional) { %>
  <%= propName %>?: <%= generateReturnType(prop.type) %>;
    <% } else { %>
  <%= propName %>: <%= generateReturnType(prop.type) %>;
    <% } %>
  <% }); %>
  <% _.forEach(events?.props, function(prop, index) { %>
    <% var propName = toReactEventName(prop.name); %>
  <%= propName %>?: <%= generateEventHandlerType(prop.type) %>;
  <% }); %>
  children?: React.ReactNode;
}

export interface <%= className %>Element extends HTMLElement {
  <% _.forEach(properties?.props, function(prop, index) { %>
    <% var propName = _.camelCase(prop.name); %>
    <% if (prop.optional) { %>
  <%= propName %>?: <%= generateReturnType(prop.type) %>;
    <% } else { %>
  <%= propName %>: <%= generateReturnType(prop.type) %>;
    <% } %>
  <% }); %>
  <% _.forEach(properties?.methods, function(method, index) { %>
  <%= generateMethodDeclaration(method) %>
  <% }); %>
}

export const <%= className %> = createComponent({
  tagName: '<%= _.kebabCase(className) %>',
  displayName: '<%= className %>',
  <% if (events) { %>
  events: {
    <% _.forEach(events?.props, function(prop, index) { %>
      <% var propName = toReactEventName(prop.name); %>
    <%= propName %>: '<%= prop.name %>',
    <% }); %>
  }
  <% } %>
}) as React.ComponentType<<%= className %>Props & { ref?: React.Ref<HTMLUnknownElement> }>
