/*
 * Generated by TSDL, don't edit this file directly.
 */

<% components.forEach(component => { %>
export { <%= component.className %>, <%= component.className %>Element } from "./<%= component.fileName %>";
<% }); %>
export { createComponent } from "./utils/createComponent";
