// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen generate --flutter-package-src=/Users/andycall/workspace/webf-enterprise-3/webf/example --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterPopupBindings extends WidgetElement {
  FlutterPopupBindings(super.context);
  bool get open;
  set open(value);
  String get title;
  set title(value);
  bool get showClose;
  set showClose(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['open'] = ElementAttributeProperty(
      getter: () => open.toString(),
      setter: (value) => open = value == 'true' || value == ''
    );
    attributes['title'] = ElementAttributeProperty(
      getter: () => title.toString(),
      setter: (value) => title = value
    );
    attributes['show-close'] = ElementAttributeProperty(
      getter: () => showClose.toString(),
      setter: (value) => showClose = value == 'true' || value == ''
    );
  }
  static StaticDefinedBindingPropertyMap flutterPopupProperties = {
    'open': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterPopupBindings>(element).open,
      setter: (element, value) =>
      castToType<FlutterPopupBindings>(element).open = value,
    ),
    'title': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterPopupBindings>(element).title,
      setter: (element, value) =>
      castToType<FlutterPopupBindings>(element).title = value,
    ),
    'showClose': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterPopupBindings>(element).showClose,
      setter: (element, value) =>
      castToType<FlutterPopupBindings>(element).showClose = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterPopupProperties,
  ];
}