// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoDatePickerBindings extends WidgetElement {
  FlutterCupertinoDatePickerBindings(super.context);
  String? get mode;
  set mode(value);
  String? get minimumDate;
  set minimumDate(value);
  String? get maximumDate;
  set maximumDate(value);
  int? get minimumYear;
  set minimumYear(value);
  int? get maximumYear;
  set maximumYear(value);
  int? get minuteInterval;
  set minuteInterval(value);
  bool get use24H;
  set use24H(value);
  bool get showDayOfWeek;
  set showDayOfWeek(value);
  String? get value;
  set value(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['mode'] = ElementAttributeProperty(
      getter: () => mode?.toString(),
      setter: (value) => mode = value,
      deleter: () => mode = null
    );
    attributes['minimum-date'] = ElementAttributeProperty(
      getter: () => minimumDate?.toString(),
      setter: (value) => minimumDate = value,
      deleter: () => minimumDate = null
    );
    attributes['maximum-date'] = ElementAttributeProperty(
      getter: () => maximumDate?.toString(),
      setter: (value) => maximumDate = value,
      deleter: () => maximumDate = null
    );
    attributes['minimum-year'] = ElementAttributeProperty(
      getter: () => minimumYear?.toString(),
      setter: (value) => minimumYear = int.tryParse(value) ?? 0,
      deleter: () => minimumYear = 0
    );
    attributes['maximum-year'] = ElementAttributeProperty(
      getter: () => maximumYear?.toString(),
      setter: (value) => maximumYear = int.tryParse(value) ?? 0,
      deleter: () => maximumYear = 0
    );
    attributes['minute-interval'] = ElementAttributeProperty(
      getter: () => minuteInterval?.toString(),
      setter: (value) => minuteInterval = int.tryParse(value) ?? 0,
      deleter: () => minuteInterval = 0
    );
    attributes['use-24-h'] = ElementAttributeProperty(
      getter: () => use24H.toString(),
      setter: (value) => use24H = value == 'true' || value == '',
      deleter: () => use24H = false
    );
    attributes['show-day-of-week'] = ElementAttributeProperty(
      getter: () => showDayOfWeek.toString(),
      setter: (value) => showDayOfWeek = value == 'true' || value == '',
      deleter: () => showDayOfWeek = false
    );
    attributes['value'] = ElementAttributeProperty(
      getter: () => value?.toString(),
      setter: (value) => this.value = value,
      deleter: () => value = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoDatePickerProperties = {
    'mode': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).mode,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).mode = value,
    ),
    'minimumDate': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).minimumDate,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).minimumDate = value,
    ),
    'maximumDate': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).maximumDate,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).maximumDate = value,
    ),
    'minimumYear': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).minimumYear,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).minimumYear = value,
    ),
    'maximumYear': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).maximumYear,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).maximumYear = value,
    ),
    'minuteInterval': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).minuteInterval,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).minuteInterval = value,
    ),
    'use24H': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).use24H,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).use24H = value,
    ),
    'showDayOfWeek': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).showDayOfWeek,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).showDayOfWeek = value,
    ),
    'value': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoDatePickerBindings>(element).value,
      setter: (element, value) =>
      castToType<FlutterCupertinoDatePickerBindings>(element).value = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoDatePickerProperties,
  ];
}
