// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoIconBindings extends WidgetElement {
  FlutterCupertinoIconBindings(super.context);
  String? get type;
  set type(value);
  String? get label;
  set label(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['type'] = ElementAttributeProperty(
      getter: () => type?.toString(),
      setter: (value) => type = value,
      deleter: () => type = null
    );
    attributes['label'] = ElementAttributeProperty(
      getter: () => label?.toString(),
      setter: (value) => label = value,
      deleter: () => label = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoIconProperties = {
    'type': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoIconBindings>(element).type,
      setter: (element, value) =>
      castToType<FlutterCupertinoIconBindings>(element).type = value,
    ),
    'label': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoIconBindings>(element).label,
      setter: (element, value) =>
      castToType<FlutterCupertinoIconBindings>(element).label = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoIconProperties,
  ];
}