// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoSearchTextFieldBindings extends WidgetElement {
  FlutterCupertinoSearchTextFieldBindings(super.context);
  String? get val;
  set val(value);
  String? get placeholder;
  set placeholder(value);
  bool get autofocus;
  set autofocus(value);
  bool get disabled;
  set disabled(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['val'] = ElementAttributeProperty(
      getter: () => val?.toString(),
      setter: (value) => val = value,
      deleter: () => val = null
    );
    attributes['placeholder'] = ElementAttributeProperty(
      getter: () => placeholder?.toString(),
      setter: (value) => placeholder = value,
      deleter: () => placeholder = null
    );
    attributes['autofocus'] = ElementAttributeProperty(
      getter: () => autofocus.toString(),
      setter: (value) => autofocus = value == 'true' || value == '',
      deleter: () => autofocus = false
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoSearchTextFieldProperties = {
    'val': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchTextFieldBindings>(element).val,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchTextFieldBindings>(element).val = value,
    ),
    'placeholder': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchTextFieldBindings>(element).placeholder,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchTextFieldBindings>(element).placeholder = value,
    ),
    'autofocus': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchTextFieldBindings>(element).autofocus,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchTextFieldBindings>(element).autofocus = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchTextFieldBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchTextFieldBindings>(element).disabled = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoSearchTextFieldProperties,
  ];
}