// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct LegacyInlineCssStyleDeclarationRustMethods {
  pub version: c_double,
  pub legacy_css_style_declaration: LegacyCssStyleDeclarationRustMethods,
}
pub struct LegacyInlineCssStyleDeclaration {
  pub legacy_css_style_declaration: LegacyCssStyleDeclaration,
  method_pointer: *const LegacyInlineCssStyleDeclarationRustMethods,
}
impl LegacyInlineCssStyleDeclaration {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const LegacyInlineCssStyleDeclarationRustMethods, status: *const RustValueStatus) -> LegacyInlineCssStyleDeclaration {
    unsafe {
      LegacyInlineCssStyleDeclaration {
        legacy_css_style_declaration: LegacyCssStyleDeclaration::initialize(
          ptr,
          context,
          &(method_pointer).as_ref().unwrap().legacy_css_style_declaration,
          status,
        ),
        method_pointer,
      }
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.legacy_css_style_declaration.ptr()
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    self.legacy_css_style_declaration.context()
  }
}
pub trait LegacyInlineCssStyleDeclarationMethods: LegacyCssStyleDeclarationMethods {
  fn as_legacy_inline_css_style_declaration(&self) -> &LegacyInlineCssStyleDeclaration;
}
impl LegacyInlineCssStyleDeclarationMethods for LegacyInlineCssStyleDeclaration {
  fn as_legacy_inline_css_style_declaration(&self) -> &LegacyInlineCssStyleDeclaration {
    self
  }
}
impl LegacyCssStyleDeclarationMethods for LegacyInlineCssStyleDeclaration {
  fn css_text(&self) -> String {
    self.legacy_css_style_declaration.css_text()
  }
  fn set_css_text(&self, value: String, exception_state: &ExceptionState) -> Result<(), String> {
    self.legacy_css_style_declaration.set_css_text(value, exception_state)
  }
  fn length(&self) -> i64 {
    self.legacy_css_style_declaration.length()
  }
  fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.legacy_css_style_declaration.get_property_value(property, exception_state)
  }
  fn set_property(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String> {
    self.legacy_css_style_declaration.set_property_with_priority(property, value, priority, exception_state)
  }
  fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.legacy_css_style_declaration.remove_property(property, exception_state)
  }
  fn as_legacy_css_style_declaration(&self) -> &LegacyCssStyleDeclaration {
    &self.legacy_css_style_declaration
  }
}
