// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
enum LegacyCssStyleDeclarationType {
  LegacyCssStyleDeclaration = 0,
  LegacyComputedCssStyleDeclaration = 1,
  LegacyInlineCssStyleDeclaration = 2,
}
#[repr(C)]
pub struct LegacyCssStyleDeclarationRustMethods {
  pub version: c_double,
  pub css_text: extern "C" fn(ptr: *const OpaquePtr) -> AtomicStringRef,
  pub set_css_text: extern "C" fn(ptr: *const OpaquePtr, value: *const c_char, exception_state: *const OpaquePtr) -> bool,
  pub length: extern "C" fn(ptr: *const OpaquePtr) -> i64,
  pub get_property_value: extern "C" fn(ptr: *const OpaquePtr, *const c_char, exception_state: *const OpaquePtr) -> AtomicStringRef,
  pub set_property: extern "C" fn(ptr: *const OpaquePtr, *const c_char, NativeValue, *const c_char, exception_state: *const OpaquePtr) -> c_void,
  pub remove_property: extern "C" fn(ptr: *const OpaquePtr, *const c_char, exception_state: *const OpaquePtr) -> AtomicStringRef,
  pub release: extern "C" fn(ptr: *const OpaquePtr) -> c_void,
  pub dynamic_to: extern "C" fn(ptr: *const OpaquePtr, type_: LegacyCssStyleDeclarationType) -> RustValue<c_void>,
}
pub struct LegacyCssStyleDeclaration {
  pub ptr: *const OpaquePtr,
  context: *const ExecutingContext,
  method_pointer: *const LegacyCssStyleDeclarationRustMethods,
  status: *const RustValueStatus
}
impl LegacyCssStyleDeclaration {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const LegacyCssStyleDeclarationRustMethods, status: *const RustValueStatus) -> LegacyCssStyleDeclaration {
    LegacyCssStyleDeclaration {
      ptr,
      context,
      method_pointer,
      status
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.ptr
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    assert!(!self.context.is_null(), "Context PTR must not be null");
    unsafe { &*self.context }
  }
  pub fn css_text(&self) -> String {
    let value = unsafe {
      ((*self.method_pointer).css_text)(self.ptr())
    };
    value.to_string()
  }
  pub fn set_css_text(&self, value: String, exception_state: &ExceptionState) -> Result<(), String> {
    unsafe {
      ((*self.method_pointer).set_css_text)(self.ptr(), CString::new(value).unwrap().as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(())
  }
  pub fn length(&self) -> i64 {
    let value = unsafe {
      ((*self.method_pointer).length)(self.ptr())
    };
    value
  }
  pub fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    let value = unsafe {
      ((*self.method_pointer).get_property_value)(self.ptr(), CString::new(property).unwrap().as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(value.to_string())
  }
  pub fn set_property(&self, property: &str, value: NativeValue, exception_state: &ExceptionState) -> Result<(), String> {
    unsafe {
      ((*self.method_pointer).set_property)(self.ptr(), CString::new(property).unwrap().as_ptr(), value, CString::new("").unwrap().as_ptr(), exception_state.ptr);
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(())
  }
  pub fn set_property_with_priority(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String> {
    unsafe {
      ((*self.method_pointer).set_property)(self.ptr(), CString::new(property).unwrap().as_ptr(), value, CString::new(priority).unwrap().as_ptr(), exception_state.ptr);
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(())
  }
  pub fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    let value = unsafe {
      ((*self.method_pointer).remove_property)(self.ptr(), CString::new(property).unwrap().as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(value.to_string())
  }
  pub fn as_legacy_computed_css_style_declaration(&self) -> Result<LegacyComputedCssStyleDeclaration, &str> {
    let raw_ptr = unsafe {
      assert!(!(*((*self).status)).disposed, "The underline C++ impl of this ptr({:?}) had been disposed", (self.method_pointer));
      ((*self.method_pointer).dynamic_to)(self.ptr, LegacyCssStyleDeclarationType::LegacyComputedCssStyleDeclaration)
    };
    if (raw_ptr.value == std::ptr::null()) {
      return Err("The type value of LegacyCssStyleDeclaration does not belong to the LegacyComputedCssStyleDeclaration type.");
    }
    Ok(LegacyComputedCssStyleDeclaration::initialize(raw_ptr.value, self.context, raw_ptr.method_pointer as *const LegacyComputedCssStyleDeclarationRustMethods, raw_ptr.status))
  }
  pub fn as_legacy_inline_css_style_declaration(&self) -> Result<LegacyInlineCssStyleDeclaration, &str> {
    let raw_ptr = unsafe {
      assert!(!(*((*self).status)).disposed, "The underline C++ impl of this ptr({:?}) had been disposed", (self.method_pointer));
      ((*self.method_pointer).dynamic_to)(self.ptr, LegacyCssStyleDeclarationType::LegacyInlineCssStyleDeclaration)
    };
    if (raw_ptr.value == std::ptr::null()) {
      return Err("The type value of LegacyCssStyleDeclaration does not belong to the LegacyInlineCssStyleDeclaration type.");
    }
    Ok(LegacyInlineCssStyleDeclaration::initialize(raw_ptr.value, self.context, raw_ptr.method_pointer as *const LegacyInlineCssStyleDeclarationRustMethods, raw_ptr.status))
  }
}
impl Drop for LegacyCssStyleDeclaration {
  fn drop(&mut self) {
    unsafe {
      ((*self.method_pointer).release)(self.ptr());
    }
  }
}
pub trait LegacyCssStyleDeclarationMethods {
  fn css_text(&self) -> String;
  fn set_css_text(&self, value: String, exception_state: &ExceptionState) -> Result<(), String>;
  fn length(&self) -> i64;
  fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String>;
  fn set_property(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String>;
  fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String>;
  fn as_legacy_css_style_declaration(&self) -> &LegacyCssStyleDeclaration;
}
impl LegacyCssStyleDeclarationMethods for LegacyCssStyleDeclaration {
  fn css_text(&self) -> String {
    self.css_text()
  }
  fn set_css_text(&self, value: String, exception_state: &ExceptionState) -> Result<(), String> {
    self.set_css_text(value, exception_state)
  }
  fn length(&self) -> i64 {
    self.length()
  }
  fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.get_property_value(property, exception_state)
  }
  fn set_property(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String> {
    self.set_property_with_priority(property, value, priority, exception_state)
  }
  fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.remove_property(property, exception_state)
  }
  fn as_legacy_css_style_declaration(&self) -> &LegacyCssStyleDeclaration {
    self
  }
}
