// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnCheckboxBindings extends WidgetElement {
  FlutterShadcnCheckboxBindings(super.context);
  bool get checked;
  set checked(value);
  bool get disabled;
  set disabled(value);
  bool get indeterminate;
  set indeterminate(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['checked'] = ElementAttributeProperty(
      getter: () => checked.toString(),
      setter: (value) => this.checked = value == 'true' || value == '',
      deleter: () => checked = false
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => this.disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
    attributes['indeterminate'] = ElementAttributeProperty(
      getter: () => indeterminate.toString(),
      setter: (value) => this.indeterminate = value == 'true' || value == '',
      deleter: () => indeterminate = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnCheckboxProperties = {
    'checked': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnCheckboxBindings>(element).checked,
      setter: (element, value) =>
      castToType<FlutterShadcnCheckboxBindings>(element).checked = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnCheckboxBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterShadcnCheckboxBindings>(element).disabled = value,
    ),
    'indeterminate': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnCheckboxBindings>(element).indeterminate,
      setter: (element, value) =>
      castToType<FlutterShadcnCheckboxBindings>(element).indeterminate = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnCheckboxProperties,
  ];
}