// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnCollapsibleBindings extends WidgetElement {
  FlutterShadcnCollapsibleBindings(super.context);
  bool get open;
  set open(value);
  bool get disabled;
  set disabled(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['open'] = ElementAttributeProperty(
      getter: () => open.toString(),
      setter: (value) => open = value == 'true' || value == '',
      deleter: () => open = false
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnCollapsibleProperties = {
    'open': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnCollapsibleBindings>(element).open,
      setter: (element, value) =>
      castToType<FlutterShadcnCollapsibleBindings>(element).open = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnCollapsibleBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterShadcnCollapsibleBindings>(element).disabled = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnCollapsibleProperties,
  ];
}