// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnDialogBindings extends WidgetElement {
  FlutterShadcnDialogBindings(super.context);
  bool get open;
  set open(value);
  bool get closeOnOutsideClick;
  set closeOnOutsideClick(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['open'] = ElementAttributeProperty(
      getter: () => open.toString(),
      setter: (value) => open = value == 'true' || value == '',
      deleter: () => open = false
    );
    attributes['close-on-outside-click'] = ElementAttributeProperty(
      getter: () => closeOnOutsideClick.toString(),
      setter: (value) => closeOnOutsideClick = value == 'true' || value == '',
      deleter: () => closeOnOutsideClick = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnDialogProperties = {
    'open': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnDialogBindings>(element).open,
      setter: (element, value) =>
      castToType<FlutterShadcnDialogBindings>(element).open = value,
    ),
    'closeOnOutsideClick': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnDialogBindings>(element).closeOnOutsideClick,
      setter: (element, value) =>
      castToType<FlutterShadcnDialogBindings>(element).closeOnOutsideClick = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnDialogProperties,
  ];
}