// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnDropdownMenuBindings extends WidgetElement {
  FlutterShadcnDropdownMenuBindings(super.context);
  bool get open;
  set open(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['open'] = ElementAttributeProperty(
      getter: () => open.toString(),
      setter: (value) => this.open = value == 'true' || value == '',
      deleter: () => open = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnDropdownMenuProperties = {
    'open': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnDropdownMenuBindings>(element).open,
      setter: (element, value) =>
      castToType<FlutterShadcnDropdownMenuBindings>(element).open = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnDropdownMenuProperties,
  ];
}