// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnIconButtonBindings extends WidgetElement {
  FlutterShadcnIconButtonBindings(super.context);
  String? get variant;
  set variant(value);
  String? get icon;
  set icon(value);
  double? get iconSize;
  set iconSize(value);
  bool get disabled;
  set disabled(value);
  bool get loading;
  set loading(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['variant'] = ElementAttributeProperty(
      getter: () => variant?.toString(),
      setter: (value) => this.variant = value,
      deleter: () => variant = null
    );
    attributes['icon'] = ElementAttributeProperty(
      getter: () => icon?.toString(),
      setter: (value) => this.icon = value,
      deleter: () => icon = null
    );
    attributes['icon-size'] = ElementAttributeProperty(
      getter: () => iconSize?.toString(),
      setter: (value) => this.iconSize = value != null ? double.tryParse(value) : null,
      deleter: () => iconSize = null
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => this.disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
    attributes['loading'] = ElementAttributeProperty(
      getter: () => loading.toString(),
      setter: (value) => this.loading = value == 'true' || value == '',
      deleter: () => loading = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnIconButtonProperties = {
    'variant': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnIconButtonBindings>(element).variant,
      setter: (element, value) =>
      castToType<FlutterShadcnIconButtonBindings>(element).variant = value,
    ),
    'icon': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnIconButtonBindings>(element).icon,
      setter: (element, value) =>
      castToType<FlutterShadcnIconButtonBindings>(element).icon = value,
    ),
    'iconSize': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnIconButtonBindings>(element).iconSize,
      setter: (element, value) =>
      castToType<FlutterShadcnIconButtonBindings>(element).iconSize = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnIconButtonBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterShadcnIconButtonBindings>(element).disabled = value,
    ),
    'loading': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnIconButtonBindings>(element).loading,
      setter: (element, value) =>
      castToType<FlutterShadcnIconButtonBindings>(element).loading = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnIconButtonProperties,
  ];
}
