// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnSkeletonBindings extends WidgetElement {
  FlutterShadcnSkeletonBindings(super.context);
  String? get width;
  set width(value);
  String? get height;
  set height(value);
  bool get circle;
  set circle(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['width'] = ElementAttributeProperty(
      getter: () => width?.toString(),
      setter: (value) => this.width = value,
      deleter: () => width = null
    );
    attributes['height'] = ElementAttributeProperty(
      getter: () => height?.toString(),
      setter: (value) => this.height = value,
      deleter: () => height = null
    );
    attributes['circle'] = ElementAttributeProperty(
      getter: () => circle.toString(),
      setter: (value) => this.circle = value == 'true' || value == '',
      deleter: () => circle = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnSkeletonProperties = {
    'width': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSkeletonBindings>(element).width,
      setter: (element, value) =>
      castToType<FlutterShadcnSkeletonBindings>(element).width = value,
    ),
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSkeletonBindings>(element).height,
      setter: (element, value) =>
      castToType<FlutterShadcnSkeletonBindings>(element).height = value,
    ),
    'circle': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSkeletonBindings>(element).circle,
      setter: (element, value) =>
      castToType<FlutterShadcnSkeletonBindings>(element).circle = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnSkeletonProperties,
  ];
}