// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnSliderBindings extends WidgetElement {
  FlutterShadcnSliderBindings(super.context);
  String? get value;
  set value(value);
  String? get min;
  set min(value);
  String? get max;
  set max(value);
  String? get step;
  set step(value);
  bool get disabled;
  set disabled(value);
  String? get orientation;
  set orientation(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['value'] = ElementAttributeProperty(
      getter: () => value?.toString(),
      setter: (value) => this.value = value,
      deleter: () => value = null
    );
    attributes['min'] = ElementAttributeProperty(
      getter: () => min?.toString(),
      setter: (value) => this.min = value,
      deleter: () => min = null
    );
    attributes['max'] = ElementAttributeProperty(
      getter: () => max?.toString(),
      setter: (value) => this.max = value,
      deleter: () => max = null
    );
    attributes['step'] = ElementAttributeProperty(
      getter: () => step?.toString(),
      setter: (value) => this.step = value,
      deleter: () => step = null
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => this.disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
    attributes['orientation'] = ElementAttributeProperty(
      getter: () => orientation?.toString(),
      setter: (value) => this.orientation = value,
      deleter: () => orientation = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnSliderProperties = {
    'value': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSliderBindings>(element).value,
      setter: (element, value) =>
      castToType<FlutterShadcnSliderBindings>(element).value = value,
    ),
    'min': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSliderBindings>(element).min,
      setter: (element, value) =>
      castToType<FlutterShadcnSliderBindings>(element).min = value,
    ),
    'max': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSliderBindings>(element).max,
      setter: (element, value) =>
      castToType<FlutterShadcnSliderBindings>(element).max = value,
    ),
    'step': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSliderBindings>(element).step,
      setter: (element, value) =>
      castToType<FlutterShadcnSliderBindings>(element).step = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSliderBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterShadcnSliderBindings>(element).disabled = value,
    ),
    'orientation': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnSliderBindings>(element).orientation,
      setter: (element, value) =>
      castToType<FlutterShadcnSliderBindings>(element).orientation = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnSliderProperties,
  ];
}