// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnTimePickerBindings extends WidgetElement {
  FlutterShadcnTimePickerBindings(super.context);
  String? get value;
  set value(value);
  String? get placeholder;
  set placeholder(value);
  bool get disabled;
  set disabled(value);
  bool get use24Hour;
  set use24Hour(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['value'] = ElementAttributeProperty(
      getter: () => value?.toString(),
      setter: (value) => this.value = value,
      deleter: () => value = null
    );
    attributes['placeholder'] = ElementAttributeProperty(
      getter: () => placeholder?.toString(),
      setter: (value) => this.placeholder = value,
      deleter: () => placeholder = null
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => this.disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
    attributes['use-24-hour'] = ElementAttributeProperty(
      getter: () => use24Hour.toString(),
      setter: (value) => this.use24Hour = value == 'true' || value == '',
      deleter: () => use24Hour = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnTimePickerProperties = {
    'value': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnTimePickerBindings>(element).value,
      setter: (element, value) =>
      castToType<FlutterShadcnTimePickerBindings>(element).value = value,
    ),
    'placeholder': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnTimePickerBindings>(element).placeholder,
      setter: (element, value) =>
      castToType<FlutterShadcnTimePickerBindings>(element).placeholder = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnTimePickerBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterShadcnTimePickerBindings>(element).disabled = value,
    ),
    'use24Hour': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnTimePickerBindings>(element).use24Hour,
      setter: (element, value) =>
      castToType<FlutterShadcnTimePickerBindings>(element).use24Hour = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnTimePickerProperties,
  ];
}