// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShadcnToastBindings extends WidgetElement {
  FlutterShadcnToastBindings(super.context);
  String? get variant;
  set variant(value);
  String? get title;
  set title(value);
  String? get description;
  set description(value);
  String? get duration;
  set duration(value);
  bool get closable;
  set closable(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['variant'] = ElementAttributeProperty(
      getter: () => variant?.toString(),
      setter: (value) => this.variant = value,
      deleter: () => variant = null
    );
    attributes['title'] = ElementAttributeProperty(
      getter: () => title?.toString(),
      setter: (value) => this.title = value,
      deleter: () => title = null
    );
    attributes['description'] = ElementAttributeProperty(
      getter: () => description?.toString(),
      setter: (value) => this.description = value,
      deleter: () => description = null
    );
    attributes['duration'] = ElementAttributeProperty(
      getter: () => duration?.toString(),
      setter: (value) => this.duration = value,
      deleter: () => duration = null
    );
    attributes['closable'] = ElementAttributeProperty(
      getter: () => closable.toString(),
      setter: (value) => this.closable = value == 'true' || value == '',
      deleter: () => closable = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterShadcnToastProperties = {
    'variant': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnToastBindings>(element).variant,
      setter: (element, value) =>
      castToType<FlutterShadcnToastBindings>(element).variant = value,
    ),
    'title': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnToastBindings>(element).title,
      setter: (element, value) =>
      castToType<FlutterShadcnToastBindings>(element).title = value,
    ),
    'description': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnToastBindings>(element).description,
      setter: (element, value) =>
      castToType<FlutterShadcnToastBindings>(element).description = value,
    ),
    'duration': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnToastBindings>(element).duration,
      setter: (element, value) =>
      castToType<FlutterShadcnToastBindings>(element).duration = value,
    ),
    'closable': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShadcnToastBindings>(element).closable,
      setter: (element, value) =>
      castToType<FlutterShadcnToastBindings>(element).closable = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShadcnToastProperties,
  ];
}