// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=. --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class WebFListViewBindings extends WidgetElement {
  WebFListViewBindings(super.context);
  String? get shrinkWrap;
  set shrinkWrap(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['shrink-wrap'] = ElementAttributeProperty(
      getter: () => shrinkWrap?.toString(),
      setter: (value) => shrinkWrap = value,
      deleter: () => shrinkWrap = null
    );
  }
  static StaticDefinedBindingPropertyMap webFListViewProperties = {
    'shrinkWrap': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFListViewBindings>(element).shrinkWrap,
      setter: (element, value) =>
      castToType<WebFListViewBindings>(element).shrinkWrap = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    webFListViewProperties,
  ];
}