/*
 * Copyright (C) 2024-present The OpenWebF Company. All rights reserved.
 * Licensed under GNU GPL with Enterprise exception.
 */
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
enum WebFTableTextDirection {
  ltr('ltr'),
  rtl('rtl');
  final String value;
  const WebFTableTextDirection(this.value);
  static WebFTableTextDirection? parse(String? value) {
    if (value == null) return null;
    return WebFTableTextDirection.values.firstWhere(
      (e) => e.value == value,
      orElse: () => throw ArgumentError('Invalid WebFTableTextDirection value: $value'),
    );
  }
  @override
  String toString() => value;
}
enum WebFTableDefaultVerticalAlignment {
  top('top'),
  middle('middle'),
  bottom('bottom'),
  baseline('baseline'),
  fill('fill');
  final String value;
  const WebFTableDefaultVerticalAlignment(this.value);
  static WebFTableDefaultVerticalAlignment? parse(String? value) {
    if (value == null) return null;
    return WebFTableDefaultVerticalAlignment.values.firstWhere(
      (e) => e.value == value,
      orElse: () => throw ArgumentError('Invalid WebFTableDefaultVerticalAlignment value: $value'),
    );
  }
  @override
  String toString() => value;
}
enum WebFTableTextBaseline {
  alphabetic('alphabetic'),
  ideographic('ideographic');
  final String value;
  const WebFTableTextBaseline(this.value);
  static WebFTableTextBaseline? parse(String? value) {
    if (value == null) return null;
    return WebFTableTextBaseline.values.firstWhere(
      (e) => e.value == value,
      orElse: () => throw ArgumentError('Invalid WebFTableTextBaseline value: $value'),
    );
  }
  @override
  String toString() => value;
}
abstract class WebFTableBindings extends WidgetElement {
  WebFTableBindings(super.context);
  WebFTableTextDirection? get textDirection;
  set textDirection(value);
  WebFTableDefaultVerticalAlignment? get defaultVerticalAlignment;
  set defaultVerticalAlignment(value);
  double? get defaultColumnWidth;
  set defaultColumnWidth(value);
  String? get columnWidths;
  set columnWidths(value);
  String? get border;
  set border(value);
  WebFTableTextBaseline? get textBaseline;
  set textBaseline(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['text-direction'] = ElementAttributeProperty(
      getter: () => textDirection?.value,
      setter: (value) => textDirection = WebFTableTextDirection.parse(value),
      deleter: () => textDirection = null
    );
    attributes['default-vertical-alignment'] = ElementAttributeProperty(
      getter: () => defaultVerticalAlignment?.value,
      setter: (value) => defaultVerticalAlignment = WebFTableDefaultVerticalAlignment.parse(value),
      deleter: () => defaultVerticalAlignment = null
    );
    attributes['default-column-width'] = ElementAttributeProperty(
      getter: () => defaultColumnWidth?.toString(),
      setter: (value) => defaultColumnWidth = double.tryParse(value) ?? 0.0,
      deleter: () => defaultColumnWidth = 0.0
    );
    attributes['column-widths'] = ElementAttributeProperty(
      getter: () => columnWidths?.toString(),
      setter: (value) => columnWidths = value,
      deleter: () => columnWidths = null
    );
    attributes['border'] = ElementAttributeProperty(
      getter: () => border?.toString(),
      setter: (value) => border = value,
      deleter: () => border = null
    );
    attributes['text-baseline'] = ElementAttributeProperty(
      getter: () => textBaseline?.value,
      setter: (value) => textBaseline = WebFTableTextBaseline.parse(value),
      deleter: () => textBaseline = null
    );
  }
  static StaticDefinedBindingPropertyMap webFTableProperties = {
    'textDirection': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableBindings>(element).textDirection,
      setter: (element, value) =>
      castToType<WebFTableBindings>(element).textDirection = value,
    ),
    'defaultVerticalAlignment': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableBindings>(element).defaultVerticalAlignment,
      setter: (element, value) =>
      castToType<WebFTableBindings>(element).defaultVerticalAlignment = value,
    ),
    'defaultColumnWidth': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableBindings>(element).defaultColumnWidth,
      setter: (element, value) =>
      castToType<WebFTableBindings>(element).defaultColumnWidth = value,
    ),
    'columnWidths': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableBindings>(element).columnWidths,
      setter: (element, value) =>
      castToType<WebFTableBindings>(element).columnWidths = value,
    ),
    'border': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableBindings>(element).border,
      setter: (element, value) =>
      castToType<WebFTableBindings>(element).border = value,
    ),
    'textBaseline': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableBindings>(element).textBaseline,
      setter: (element, value) =>
      castToType<WebFTableBindings>(element).textBaseline = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    webFTableProperties,
  ];
}