// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=/Users/andycall/workspace/webf-enterprise-2/webf --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class WebFTableHeaderBindings extends WidgetElement {
  WebFTableHeaderBindings(super.context);
  String? get backgroundColor;
  set backgroundColor(value);
  String? get color;
  set color(value);
  bool get sticky;
  set sticky(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['background-color'] = ElementAttributeProperty(
      getter: () => backgroundColor?.toString(),
      setter: (value) => backgroundColor = value,
      deleter: () => backgroundColor = null
    );
    attributes['color'] = ElementAttributeProperty(
      getter: () => color?.toString(),
      setter: (value) => color = value,
      deleter: () => color = null
    );
    attributes['sticky'] = ElementAttributeProperty(
      getter: () => sticky.toString(),
      setter: (value) => sticky = value == 'true' || value == '',
      deleter: () => sticky = false
    );
  }
  static StaticDefinedBindingPropertyMap webFTableHeaderProperties = {
    'backgroundColor': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableHeaderBindings>(element).backgroundColor,
      setter: (element, value) =>
      castToType<WebFTableHeaderBindings>(element).backgroundColor = value,
    ),
    'color': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableHeaderBindings>(element).color,
      setter: (element, value) =>
      castToType<WebFTableHeaderBindings>(element).color = value,
    ),
    'sticky': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableHeaderBindings>(element).sticky,
      setter: (element, value) =>
      castToType<WebFTableHeaderBindings>(element).sticky = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    webFTableHeaderProperties,
  ];
}