/*
 * Copyright (C) 2024-present The OpenWebF Company. All rights reserved.
 * Licensed under GNU GPL with Enterprise exception.
 */
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class WebFTableHeaderBindings extends WidgetElement {
  WebFTableHeaderBindings(super.context);
  bool get sticky;
  set sticky(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['sticky'] = ElementAttributeProperty(
      getter: () => sticky.toString(),
      setter: (value) => sticky = value == 'true' || value == '',
      deleter: () => sticky = false
    );
  }
  static StaticDefinedBindingPropertyMap webFTableHeaderProperties = {
    'sticky': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableHeaderBindings>(element).sticky,
      setter: (element, value) =>
      castToType<WebFTableHeaderBindings>(element).sticky = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    webFTableHeaderProperties,
  ];
}