// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=/Users/andycall/workspace/webf-enterprise-2/webf --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class WebFTableRowBindings extends WidgetElement {
  WebFTableRowBindings(super.context);
  double? get index;
  set index(value);
  bool get highlighted;
  set highlighted(value);
  bool get clickable;
  set clickable(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['index'] = ElementAttributeProperty(
      getter: () => index?.toString(),
      setter: (value) => index = double.tryParse(value) ?? 0.0,
      deleter: () => index = 0.0
    );
    attributes['highlighted'] = ElementAttributeProperty(
      getter: () => highlighted.toString(),
      setter: (value) => highlighted = value == 'true' || value == '',
      deleter: () => highlighted = false
    );
    attributes['clickable'] = ElementAttributeProperty(
      getter: () => clickable.toString(),
      setter: (value) => clickable = value == 'true' || value == '',
      deleter: () => clickable = false
    );
  }
  static StaticDefinedBindingPropertyMap webFTableRowProperties = {
    'index': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableRowBindings>(element).index,
      setter: (element, value) =>
      castToType<WebFTableRowBindings>(element).index = value,
    ),
    'highlighted': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableRowBindings>(element).highlighted,
      setter: (element, value) =>
      castToType<WebFTableRowBindings>(element).highlighted = value,
    ),
    'clickable': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFTableRowBindings>(element).clickable,
      setter: (element, value) =>
      castToType<WebFTableRowBindings>(element).clickable = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    webFTableRowProperties,
  ];
}