// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCameraBindings extends WidgetElement {
  FlutterCameraBindings(super.context);
  String? get facing;
  set facing(value);
  String? get resolution;
  set resolution(value);
  String? get flashMode;
  set flashMode(value);
  bool get enableAudio;
  set enableAudio(value);
  bool get autoInit;
  set autoInit(value);
  double? get zoom;
  set zoom(value);
  double? get exposureOffset;
  set exposureOffset(value);
  String? get focusMode;
  set focusMode(value);
  String? get exposureMode;
  set exposureMode(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['facing'] = ElementAttributeProperty(
      getter: () => facing?.toString(),
      setter: (value) => facing = value,
      deleter: () => facing = null
    );
    attributes['resolution'] = ElementAttributeProperty(
      getter: () => resolution?.toString(),
      setter: (value) => resolution = value,
      deleter: () => resolution = null
    );
    attributes['flash-mode'] = ElementAttributeProperty(
      getter: () => flashMode?.toString(),
      setter: (value) => flashMode = value,
      deleter: () => flashMode = null
    );
    attributes['enable-audio'] = ElementAttributeProperty(
      getter: () => enableAudio.toString(),
      setter: (value) => enableAudio = value == 'true' || value == '',
      deleter: () => enableAudio = false
    );
    attributes['auto-init'] = ElementAttributeProperty(
      getter: () => autoInit.toString(),
      setter: (value) => autoInit = value == 'true' || value == '',
      deleter: () => autoInit = false
    );
    attributes['zoom'] = ElementAttributeProperty(
      getter: () => zoom?.toString(),
      setter: (value) => zoom = double.tryParse(value) ?? 0.0,
      deleter: () => zoom = 0.0
    );
    attributes['exposure-offset'] = ElementAttributeProperty(
      getter: () => exposureOffset?.toString(),
      setter: (value) => exposureOffset = double.tryParse(value) ?? 0.0,
      deleter: () => exposureOffset = 0.0
    );
    attributes['focus-mode'] = ElementAttributeProperty(
      getter: () => focusMode?.toString(),
      setter: (value) => focusMode = value,
      deleter: () => focusMode = null
    );
    attributes['exposure-mode'] = ElementAttributeProperty(
      getter: () => exposureMode?.toString(),
      setter: (value) => exposureMode = value,
      deleter: () => exposureMode = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterCameraProperties = {
    'facing': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).facing,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).facing = value,
    ),
    'resolution': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).resolution,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).resolution = value,
    ),
    'flashMode': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).flashMode,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).flashMode = value,
    ),
    'enableAudio': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).enableAudio,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).enableAudio = value,
    ),
    'autoInit': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).autoInit,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).autoInit = value,
    ),
    'zoom': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).zoom,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).zoom = value,
    ),
    'exposureOffset': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).exposureOffset,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).exposureOffset = value,
    ),
    'focusMode': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).focusMode,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).focusMode = value,
    ),
    'exposureMode': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCameraBindings>(element).exposureMode,
      setter: (element, value) =>
      castToType<FlutterCameraBindings>(element).exposureMode = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCameraProperties,
  ];
}