/*
 * Copyright (C) 2024-present The OpenWebF Company. All rights reserved.
 * Licensed under GNU GPL with Enterprise exception.
 */
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterShimmerButtonBindings extends WidgetElement {
  FlutterShimmerButtonBindings(super.context);
  String? get width;
  set width(value);
  String? get height;
  set height(value);
  String? get radius;
  set radius(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['width'] = ElementAttributeProperty(
      getter: () => width?.toString(),
      setter: (value) => width = value,
      deleter: () => width = null
    );
    attributes['height'] = ElementAttributeProperty(
      getter: () => height?.toString(),
      setter: (value) => height = value,
      deleter: () => height = null
    );
    attributes['radius'] = ElementAttributeProperty(
      getter: () => radius?.toString(),
      setter: (value) => radius = value,
      deleter: () => radius = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterShimmerButtonProperties = {
    'width': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShimmerButtonBindings>(element).width,
      setter: (element, value) =>
      castToType<FlutterShimmerButtonBindings>(element).width = value,
    ),
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShimmerButtonBindings>(element).height,
      setter: (element, value) =>
      castToType<FlutterShimmerButtonBindings>(element).height = value,
    ),
    'radius': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterShimmerButtonBindings>(element).radius,
      setter: (element, value) =>
      castToType<FlutterShimmerButtonBindings>(element).radius = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterShimmerButtonProperties,
  ];
}