// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct ErrorEventRustMethods {
  pub version: c_double,
  pub event: EventRustMethods,
  pub message: extern "C" fn(*const OpaquePtr) -> AtomicStringRef,
  pub filename: extern "C" fn(*const OpaquePtr) -> AtomicStringRef,
  pub lineno: extern "C" fn(*const OpaquePtr) -> c_double,
  pub colno: extern "C" fn(*const OpaquePtr) -> c_double,
  pub error: extern "C" fn(*const OpaquePtr, *const OpaquePtr) -> NativeValue,
}
pub struct ErrorEvent {
  pub event: Event,
  method_pointer: *const ErrorEventRustMethods,
}
impl ErrorEvent {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const ErrorEventRustMethods, status: *const RustValueStatus) -> ErrorEvent {
    unsafe {
      ErrorEvent {
        event: Event::initialize(
          ptr,
          context,
          &(method_pointer).as_ref().unwrap().event,
          status,
        ),
        method_pointer,
      }
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.event.ptr()
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    self.event.context()
  }
  pub fn message(&self) -> String {
    let value = unsafe {
      ((*self.method_pointer).message)(self.ptr())
    };
    value.to_string()
  }
  pub fn filename(&self) -> String {
    let value = unsafe {
      ((*self.method_pointer).filename)(self.ptr())
    };
    value.to_string()
  }
  pub fn lineno(&self) -> f64 {
    let value = unsafe {
      ((*self.method_pointer).lineno)(self.ptr())
    };
    value
  }
  pub fn colno(&self) -> f64 {
    let value = unsafe {
      ((*self.method_pointer).colno)(self.ptr())
    };
    value
  }
  pub fn error(&self, exception_state: &ExceptionState) -> NativeValue {
    let value = unsafe {
      ((*self.method_pointer).error)(self.ptr(), exception_state.ptr)
    };
    value
  }
}
pub trait ErrorEventMethods: EventMethods {
  fn message(&self) -> String;
  fn filename(&self) -> String;
  fn lineno(&self) -> f64;
  fn colno(&self) -> f64;
  fn error(&self, exception_state: &ExceptionState) -> NativeValue;
  fn as_error_event(&self) -> &ErrorEvent;
}
impl ErrorEventMethods for ErrorEvent {
  fn message(&self) -> String {
    self.message()
  }
  fn filename(&self) -> String {
    self.filename()
  }
  fn lineno(&self) -> f64 {
    self.lineno()
  }
  fn colno(&self) -> f64 {
    self.colno()
  }
  fn error(&self, exception_state: &ExceptionState) -> NativeValue {
    self.error(exception_state)
  }
  fn as_error_event(&self) -> &ErrorEvent {
    self
  }
}
impl EventMethods for ErrorEvent {
  fn bubbles(&self) -> bool {
    self.event.bubbles()
  }
  fn cancel_bubble(&self) -> bool {
    self.event.cancel_bubble()
  }
  fn set_cancel_bubble(&self, value: bool, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.set_cancel_bubble(value, exception_state)
  }
  fn cancelable(&self) -> bool {
    self.event.cancelable()
  }
  fn current_target(&self) -> EventTarget {
    self.event.current_target()
  }
  fn default_prevented(&self) -> bool {
    self.event.default_prevented()
  }
  fn src_element(&self) -> EventTarget {
    self.event.src_element()
  }
  fn target(&self) -> EventTarget {
    self.event.target()
  }
  fn is_trusted(&self) -> bool {
    self.event.is_trusted()
  }
  fn time_stamp(&self) -> f64 {
    self.event.time_stamp()
  }
  fn type_(&self) -> String {
    self.event.type_()
  }
  fn init_event(&self, type_: &str, bubbles: bool, cancelable: bool, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.init_event(type_, bubbles, cancelable, exception_state)
  }
  fn prevent_default(&self, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.prevent_default(exception_state)
  }
  fn stop_immediate_propagation(&self, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.stop_immediate_propagation(exception_state)
  }
  fn stop_propagation(&self, exception_state: &ExceptionState) -> Result<(), String> {
    self.event.stop_propagation(exception_state)
  }
  fn as_event(&self) -> &Event {
    &self.event
  }
}
impl ExecutingContext {
  pub fn create_error_event(&self, event_type: &str, exception_state: &ExceptionState) -> Result<ErrorEvent, String> {
    let event_type_c_string = CString::new(event_type).unwrap();
    let new_event = unsafe {
      ((*self.method_pointer()).create_error_event)(self.ptr, event_type_c_string.as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self));
    }
    return Ok(ErrorEvent::initialize(new_event.value, self, new_event.method_pointer, new_event.status));
  }
  pub fn create_error_event_with_options(&self, event_type: &str, options: &ErrorEventInit,  exception_state: &ExceptionState) -> Result<ErrorEvent, String> {
    let event_type_c_string = CString::new(event_type).unwrap();
    let new_event = unsafe {
      ((*self.method_pointer()).create_error_event_with_options)(self.ptr, event_type_c_string.as_ptr(), options, exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self));
    }
    return Ok(ErrorEvent::initialize(new_event.value, self, new_event.method_pointer, new_event.status));
  }
}
