// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct PointerEventInit {
  pub detail: c_double,
  pub view: RustValue<WindowRustMethods>,
  pub which: c_double,
  pub bubbles: i32,
  pub cancelable: i32,
  pub composed: i32,
  pub is_primary: i32,
  pub pointer_id: c_double,
  pub pointer_type: *const c_char,
  pub pressure: c_double,
  pub tangential_pressure: c_double,
  pub tilt_x: c_double,
  pub tilt_y: c_double,
  pub twist: c_double,
  pub width: c_double,
  pub height: c_double,
}
