import {DOMMatrixInit} from "./dom_matrix_init";
import {DOMMatrix} from "./dom_matrix";
import {DOMPoint} from "./dom_point";

interface DOMMatrixReadOnly {
    readonly is2D: SupportAsync<DartImpl<boolean>>;
    readonly isIdentity: SupportAsync<DartImpl<boolean>>;
    m11: number;
    m12: number;
    m13: number;
    m14: number;
    m21: number;
    m22: number;
    m23: number;
    m24: number;
    m31: number;
    m32: number;
    m33: number;
    m34: number;
    m41: number;
    m42: number;
    m43: number;
    m44: number;
    a: number;
    b: number;
    c: number;
    d: number;
    e: number;
    f: number;
    flipX(): SupportAsync<DOMMatrix>;
    flipY(): SupportAsync<DOMMatrix>;
    inverse(): SupportAsync<DOMMatrix>;
    multiply(matrix: DOMMatrix): SupportAsync<DOMMatrix>;
    rotateAxisAngle(x?:number, y?:number, z?:number, angle?:number): SupportAsync<DOMMatrix>;
    rotate(x?:number, y?:number, z?:number): SupportAsync<DOMMatrix>;
    rotateFromVector(x?:number, y?:number): SupportAsync<DOMMatrix>;
    scale(sx?: number, sy?: number, sz?: number, ox?: number, oy?: number, oz?: number): SupportAsync<DOMMatrix>;
    scale3d(scale?: number, ox?: number, oy?: number, oz?: number): SupportAsync<DOMMatrix>;
    scaleNonUniform(sx?: number, sy?: number): SupportAsync<DOMMatrix>;
    skewX(sx?: number): SupportAsync<DOMMatrix>;
    skewY(sy?: number): SupportAsync<DOMMatrix>;
    // toFloat32Array(): number[];
    // toFloat64Array(): number[];
    // TODO
    // toJSON(): DartImpl<JSON>;
    toString(): string;
    transformPoint(point: DOMPoint): SupportAsync<DOMPoint>;
    translate(tx?:number, ty?:number, tz?:number): SupportAsync<DOMMatrix>;
    // fromFloat32Array(): StaticMethod<DOMMatrix>;
    // fromFloat64Array(): StaticMethod<DOMMatrix>;
    fromMatrix(matrix: DOMMatrix): StaticMethod<DOMMatrix>;
    new(init?: number[] | DOMMatrixInit): DOMMatrixReadOnly;
}