import {DOMMatrixInit} from "./dom_matrix_init";
import {DOMMatrix} from "./dom_matrix";
import {DOMPoint} from "./dom_point";

interface DOMMatrixReadOnly {
    readonly is2D: SupportAsync<DartImpl<boolean>>;
    readonly isIdentity: SupportAsync<DartImpl<boolean>>;
    m11: SupportAsync<number>;
    m12: SupportAsync<number>;
    m13: SupportAsync<number>;
    m14: SupportAsync<number>;
    m21: SupportAsync<number>;
    m22: SupportAsync<number>;
    m23: SupportAsync<number>;
    m24: SupportAsync<number>;
    m31: SupportAsync<number>;
    m32: SupportAsync<number>;
    m33: SupportAsync<number>;
    m34: SupportAsync<number>;
    m41: SupportAsync<number>;
    m42: SupportAsync<number>;
    m43: SupportAsync<number>;
    m44: SupportAsync<number>;
    a: SupportAsync<number>;
    b: SupportAsync<number>;
    c: SupportAsync<number>;
    d: SupportAsync<number>;
    e: SupportAsync<number>;
    f: SupportAsync<number>;
    flipX(): SupportAsync<DOMMatrix>;
    flipY(): SupportAsync<DOMMatrix>;
    inverse(): SupportAsync<DOMMatrix>;
    multiply(matrix: DOMMatrix): SupportAsync<DOMMatrix>;
    rotateAxisAngle(x?:number, y?:number, z?:number, angle?:number): SupportAsync<DOMMatrix>;
    rotate(x?:number, y?:number, z?:number): SupportAsync<DOMMatrix>;
    rotateFromVector(x?:number, y?:number): SupportAsync<DOMMatrix>;
    scale(sx?: number, sy?: number, sz?: number, ox?: number, oy?: number, oz?: number): SupportAsync<DOMMatrix>;
    scale3d(scale?: number, ox?: number, oy?: number, oz?: number): SupportAsync<DOMMatrix>;
    scaleNonUniform(sx?: number, sy?: number): SupportAsync<DOMMatrix>;
    skewX(sx?: number): SupportAsync<DOMMatrix>;
    skewY(sy?: number): SupportAsync<DOMMatrix>;
    // toFloat32Array(): number[];
    // toFloat64Array(): number[];
    // TODO
    // toJSON(): DartImpl<JSON>;
    toString(): SupportAsync<string>;
    transformPoint(point: DOMPoint): SupportAsync<DOMPoint>;
    translate(tx?:number, ty?:number, tz?:number): SupportAsync<DOMMatrix>;
    // fromFloat32Array(): StaticMethod<DOMMatrix>;
    // fromFloat64Array(): StaticMethod<DOMMatrix>;
    fromMatrix(matrix: DOMMatrix): StaticMethod<DOMMatrix>;
    new(init?: number[] | DOMMatrixInit): DOMMatrixReadOnly;
}