/*
 * Generated by TSDL, don't edit this file directly.
 */
import React, { EventHandler, SyntheticEvent } from "react";
import { createComponent } from "../../utils/createComponent";
interface FlutterCupertinoCheckboxProps {
  val?: string;
  disabled?: boolean;
  activeColor?: string;
  checkColor?: string;
  focusColor?: string;
  fillColorSelected?: string;
  fillColorDisabled?: string;
  onChange?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}
export interface FlutterCupertinoCheckboxElement extends HTMLElement {
  val?: string;
  disabled?: boolean;
  activeColor?: string;
  checkColor?: string;
  focusColor?: string;
  fillColorSelected?: string;
  fillColorDisabled?: string;
}
export const FlutterCupertinoCheckbox = createComponent({
  tagName: 'flutter-cupertino-checkbox',
  displayName: 'FlutterCupertinoCheckbox',
  events: {
    onChange: 'change',
  }
}) as React.ComponentType<FlutterCupertinoCheckboxProps & { ref?: React.Ref<HTMLUnknownElement> }>