/*
 * Generated by TSDL, don't edit this file directly.
 */
import React, { EventHandler, SyntheticEvent } from "react";
import { createComponent } from "../../utils/createComponent";
interface FlutterCupertinoInputProps {
  val?: string;
  placeholder?: string;
  type?: string;
  disabled?: boolean;
  autofocus: boolean;
  clearable?: boolean;
  maxlength?: number;
  readonly?: boolean;
  onInput?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  onSubmit?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}
export interface FlutterCupertinoInputElement extends HTMLElement {
  val?: string;
  placeholder?: string;
  type?: string;
  disabled?: boolean;
  autofocus: boolean;
  clearable?: boolean;
  maxlength?: number;
  readonly?: boolean;
  getValue(): string;
  setValue(value: string): void;
  focus(): void;
  blur(): void;
}
export const FlutterCupertinoInput = createComponent({
  tagName: 'flutter-cupertino-input',
  displayName: 'FlutterCupertinoInput',
  events: {
    onInput: 'input',
    onSubmit: 'submit',
  }
}) as React.ComponentType<FlutterCupertinoInputProps & { ref?: React.Ref<HTMLUnknownElement> }>