/*
 * Generated by TSDL, don't edit this file directly.
 */
import React, { EventHandler, SyntheticEvent } from "react";
import { createComponent } from "../../utils/createComponent";
interface FlutterCupertinoModalPopupProps {
  visible?: boolean;
  height?: number;
  surfacePainted?: boolean;
  maskClosable?: boolean;
  backgroundOpacity?: number;
  onClose?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}
export interface FlutterCupertinoModalPopupElement extends HTMLElement {
  visible?: boolean;
  height?: number;
  surfacePainted?: boolean;
  maskClosable?: boolean;
  backgroundOpacity?: number;
  show(): void;
  hide(): void;
}
export const FlutterCupertinoModalPopup = createComponent({
  tagName: 'flutter-cupertino-modal-popup',
  displayName: 'FlutterCupertinoModalPopup',
  events: {
    onClose: 'close',
  }
}) as React.ComponentType<FlutterCupertinoModalPopupProps & { ref?: React.Ref<HTMLUnknownElement> }>