/*
 * Generated by TSDL, don't edit this file directly.
 */
import React, { EventHandler, SyntheticEvent } from "react";
import { createComponent } from "../../utils/createComponent";
interface FlutterCupertinoSearchInputProps {
  val?: string;
  placeholder?: string;
  disabled?: boolean;
  type?: string;
  prefixIcon?: string;
  suffixIcon?: string;
  suffixModel?: string;
  itemColor?: string;
  itemSize?: number;
  autofocus: boolean;
  onInput?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  onSearch?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  onClear?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}
export interface FlutterCupertinoSearchInputElement extends HTMLElement {
  val?: string;
  placeholder?: string;
  disabled?: boolean;
  type?: string;
  prefixIcon?: string;
  suffixIcon?: string;
  suffixModel?: string;
  itemColor?: string;
  itemSize?: number;
  autofocus: boolean;
  getValue(): string;
  setValue(value: string): void;
  focus(): void;
  blur(): void;
  clear(): void;
}
export const FlutterCupertinoSearchInput = createComponent({
  tagName: 'flutter-cupertino-search-input',
  displayName: 'FlutterCupertinoSearchInput',
  events: {
    onInput: 'input',
    onSearch: 'search',
    onClear: 'clear',
  }
}) as React.ComponentType<FlutterCupertinoSearchInputProps & { ref?: React.Ref<HTMLUnknownElement> }>