/*
 * Generated by TSDL, don't edit this file directly.
 */
import React, { EventHandler, SyntheticEvent } from "react";
import { createComponent } from "../../utils/createComponent";
interface FlutterCupertinoSliderProps {
  val?: number;
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  onChange?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  onChangestart?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  onChangeend?: EventHandler<SyntheticEvent<Element, CustomEvent>>;
  style?: React.CSSProperties;
  children?: React.ReactNode;
}
export interface FlutterCupertinoSliderElement extends HTMLElement {
  val?: number;
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  getValue(): number;
  setValue(val: number): void;
}
export const FlutterCupertinoSlider = createComponent({
  tagName: 'flutter-cupertino-slider',
  displayName: 'FlutterCupertinoSlider',
  events: {
    onChange: 'change',
    onChangestart: 'changestart',
    onChangeend: 'changeend',
  }
}) as React.ComponentType<FlutterCupertinoSliderProps & { ref?: React.Ref<HTMLUnknownElement> }>