// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct HashchangeEventInit {
  pub bubbles: bool,
  pub cancelable: bool,
  pub composed: bool,
  pub old_url: *const c_char,
  pub new_url: *const c_char,
}