// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct TouchInit {
  pub identifier: c_double,
  pub target: RustValue<EventTargetRustMethods>,
  pub client_x: c_double,
  pub client_y: c_double,
  pub screen_x: c_double,
  pub screen_y: c_double,
  pub page_x: c_double,
  pub page_y: c_double,
  pub radius_x: c_double,
  pub radius_y: c_double,
  pub rotation_angle: c_double,
  pub force: c_double,
}