// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct TransitionEventInit {
  pub bubbles: bool,
  pub cancelable: bool,
  pub composed: bool,
  pub elapsed_time: c_double,
  pub property_name: *const c_char,
  pub pseudo_element: *const c_char,
}