// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js

/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */

#ifndef WEBF_CORE_WEBF_API_<%= blob.filename.toUpperCase() %>_H_
#define WEBF_CORE_WEBF_API_<%= blob.filename.toUpperCase() %>_H_
#include <stdint.h>
<%= content %>

#endif // WEBF_CORE_WEBF_API_<%= blob.filename.toUpperCase() %>_H_
