// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct CSSStyleSheetInit {
  pub media: RustValue<MediaListRustMethods>,
  pub disabled: i32,
  pub alternate: i32,
  pub title: AtomicStringRef,
}
