// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
pub struct InlineCssStyleDeclarationRustMethods {
  pub version: c_double,
  pub css_style_declaration: CSSStyleDeclarationRustMethods,
  pub get_property_value: extern "C" fn(ptr: *const OpaquePtr, *const c_char, exception_state: *const OpaquePtr) -> AtomicStringRef,
  pub set_property: extern "C" fn(ptr: *const OpaquePtr, *const c_char, NativeValue, *const c_char, exception_state: *const OpaquePtr) -> c_void,
  pub remove_property: extern "C" fn(ptr: *const OpaquePtr, *const c_char, exception_state: *const OpaquePtr) -> AtomicStringRef,
}
pub struct InlineCssStyleDeclaration {
  pub css_style_declaration: CSSStyleDeclaration,
  method_pointer: *const InlineCssStyleDeclarationRustMethods,
}
impl InlineCssStyleDeclaration {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const InlineCssStyleDeclarationRustMethods, status: *const RustValueStatus) -> InlineCssStyleDeclaration {
    unsafe {
      InlineCssStyleDeclaration {
        css_style_declaration: CSSStyleDeclaration::initialize(
          ptr,
          context,
          &(method_pointer).as_ref().unwrap().css_style_declaration,
          status,
        ),
        method_pointer,
      }
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.css_style_declaration.ptr()
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    self.css_style_declaration.context()
  }
  pub fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    let value = unsafe {
      ((*self.method_pointer).get_property_value)(self.ptr(), CString::new(property).unwrap().as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(value.to_string())
  }
  pub fn set_property(&self, property: &str, value: NativeValue, exception_state: &ExceptionState) -> Result<(), String> {
    unsafe {
      ((*self.method_pointer).set_property)(self.ptr(), CString::new(property).unwrap().as_ptr(), value, CString::new("").unwrap().as_ptr(), exception_state.ptr);
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(())
  }
  pub fn set_property_with_priority(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String> {
    unsafe {
      ((*self.method_pointer).set_property)(self.ptr(), CString::new(property).unwrap().as_ptr(), value, CString::new(priority).unwrap().as_ptr(), exception_state.ptr);
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(())
  }
  pub fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    let value = unsafe {
      ((*self.method_pointer).remove_property)(self.ptr(), CString::new(property).unwrap().as_ptr(), exception_state.ptr)
    };
    if exception_state.has_exception() {
      return Err(exception_state.stringify(self.context()));
    }
    Ok(value.to_string())
  }
}
pub trait InlineCssStyleDeclarationMethods: CSSStyleDeclarationMethods {
  fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String>;
  fn set_property(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String>;
  fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String>;
  fn as_inline_css_style_declaration(&self) -> &InlineCssStyleDeclaration;
}
impl InlineCssStyleDeclarationMethods for InlineCssStyleDeclaration {
  fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.get_property_value(property, exception_state)
  }
  fn set_property(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String> {
    self.set_property_with_priority(property, value, priority, exception_state)
  }
  fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.remove_property(property, exception_state)
  }
  fn as_inline_css_style_declaration(&self) -> &InlineCssStyleDeclaration {
    self
  }
}
impl CSSStyleDeclarationMethods for InlineCssStyleDeclaration {
  fn css_text(&self) -> String {
    self.css_style_declaration.css_text()
  }
  fn set_css_text(&self, value: String, exception_state: &ExceptionState) -> Result<(), String> {
    self.css_style_declaration.set_css_text(value, exception_state)
  }
  fn length(&self) -> i64 {
    self.css_style_declaration.length()
  }
  fn get_property_value(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.css_style_declaration.get_property_value(property, exception_state)
  }
  fn set_property(&self, property: &str, value: NativeValue, priority: &str, exception_state: &ExceptionState) -> Result<(), String> {
    self.css_style_declaration.set_property_with_priority(property, value, priority, exception_state)
  }
  fn remove_property(&self, property: &str, exception_state: &ExceptionState) -> Result<String, String> {
    self.css_style_declaration.remove_property(property, exception_state)
  }
  fn as_css_style_declaration(&self) -> &CSSStyleDeclaration {
    &self.css_style_declaration
  }
}
