/*
 * Copyright (C) 2024-present The OpenWebF Company. All rights reserved.
 * Licensed under GNU GPL with Enterprise exception.
 */
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
enum FlutterFormLayout {
  vertical('vertical'),
  horizontal('horizontal');
  final String value;
  const FlutterFormLayout(this.value);
  static FlutterFormLayout? parse(String? value) {
    if (value == null) return null;
    return FlutterFormLayout.values.firstWhere(
      (e) => e.value == value,
      orElse: () => throw ArgumentError('Invalid FlutterFormLayout value: $value'),
    );
  }
  @override
  String toString() => value;
}
abstract class FlutterFormBindings extends WidgetElement {
  FlutterFormBindings(super.context);
  bool get autovalidate;
  set autovalidate(value);
  bool get validateOnSubmit;
  set validateOnSubmit(value);
  FlutterFormLayout? get layout;
  set layout(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['autovalidate'] = ElementAttributeProperty(
      getter: () => autovalidate.toString(),
      setter: (value) => autovalidate = value == 'true' || value == '',
      deleter: () => autovalidate = false
    );
    attributes['validate-on-submit'] = ElementAttributeProperty(
      getter: () => validateOnSubmit.toString(),
      setter: (value) => validateOnSubmit = value == 'true' || value == '',
      deleter: () => validateOnSubmit = false
    );
    attributes['layout'] = ElementAttributeProperty(
      getter: () => layout?.value,
      setter: (value) => layout = FlutterFormLayout.parse(value),
      deleter: () => layout = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterFormProperties = {
    'autovalidate': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterFormBindings>(element).autovalidate,
      setter: (element, value) =>
      castToType<FlutterFormBindings>(element).autovalidate = value,
    ),
    'validateOnSubmit': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterFormBindings>(element).validateOnSubmit,
      setter: (element, value) =>
      castToType<FlutterFormBindings>(element).validateOnSubmit = value,
    ),
    'layout': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterFormBindings>(element).layout,
      setter: (element, value) =>
      castToType<FlutterFormBindings>(element).layout = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterFormProperties,
  ];
}