// Generated by WebF TSDL, don't edit this file directly.
// Generate command: node scripts/generate_binding_code.js
/*
* Copyright (C) 2022-present The WebF authors. All rights reserved.
*/
use std::ffi::*;
use crate::*;
#[repr(C)]
enum CanvasRenderingContextType {
  CanvasRenderingContext = 0,
}
#[repr(C)]
pub struct CanvasRenderingContextRustMethods {
  pub version: c_double,
  pub release: extern "C" fn(ptr: *const OpaquePtr) -> c_void,
  pub dynamic_to: extern "C" fn(ptr: *const OpaquePtr, type_: CanvasRenderingContextType) -> RustValue<c_void>,
}
pub struct CanvasRenderingContext {
  pub ptr: *const OpaquePtr,
  context: *const ExecutingContext,
  method_pointer: *const CanvasRenderingContextRustMethods,
  status: *const RustValueStatus
}
impl CanvasRenderingContext {
  pub fn initialize(ptr: *const OpaquePtr, context: *const ExecutingContext, method_pointer: *const CanvasRenderingContextRustMethods, status: *const RustValueStatus) -> CanvasRenderingContext {
    CanvasRenderingContext {
      ptr,
      context,
      method_pointer,
      status
    }
  }
  pub fn ptr(&self) -> *const OpaquePtr {
    self.ptr
  }
  pub fn context<'a>(&self) -> &'a ExecutingContext {
    assert!(!self.context.is_null(), "Context PTR must not be null");
    unsafe { &*self.context }
  }
}
impl Drop for CanvasRenderingContext {
  fn drop(&mut self) {
    unsafe {
      ((*self.method_pointer).release)(self.ptr());
    }
  }
}
pub trait CanvasRenderingContextMethods {
  fn as_canvas_rendering_context(&self) -> &CanvasRenderingContext;
}
impl CanvasRenderingContextMethods for CanvasRenderingContext {
  fn as_canvas_rendering_context(&self) -> &CanvasRenderingContext {
    self
  }
}
