// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class WebFVideoPlayerBindings extends WidgetElement {
  WebFVideoPlayerBindings(super.context);
  String? get src;
  set src(value);
  String? get poster;
  set poster(value);
  bool get autoplay;
  set autoplay(value);
  bool get controls;
  set controls(value);
  bool get loop;
  set loop(value);
  bool get muted;
  set muted(value);
  double? get volume;
  set volume(value);
  double? get playbackRate;
  set playbackRate(value);
  double? get currentTime;
  set currentTime(value);
  String? get objectFit;
  set objectFit(value);
  String? get preload;
  set preload(value);
  bool get playsInline;
  set playsInline(value);
  double? get duration;
  set duration(value);
  bool get paused;
  set paused(value);
  bool get ended;
  set ended(value);
  bool get seeking;
  set seeking(value);
  int? get readyState;
  set readyState(value);
  int? get networkState;
  set networkState(value);
  int? get videoWidth;
  set videoWidth(value);
  int? get videoHeight;
  set videoHeight(value);
  bool get buffering;
  set buffering(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['src'] = ElementAttributeProperty(
      getter: () => src?.toString(),
      setter: (value) => src = value,
      deleter: () => src = null
    );
    attributes['poster'] = ElementAttributeProperty(
      getter: () => poster?.toString(),
      setter: (value) => poster = value,
      deleter: () => poster = null
    );
    attributes['autoplay'] = ElementAttributeProperty(
      getter: () => autoplay.toString(),
      setter: (value) => autoplay = value == 'true' || value == '',
      deleter: () => autoplay = false
    );
    attributes['controls'] = ElementAttributeProperty(
      getter: () => controls.toString(),
      setter: (value) => controls = value == 'true' || value == '',
      deleter: () => controls = false
    );
    attributes['loop'] = ElementAttributeProperty(
      getter: () => loop.toString(),
      setter: (value) => loop = value == 'true' || value == '',
      deleter: () => loop = false
    );
    attributes['muted'] = ElementAttributeProperty(
      getter: () => muted.toString(),
      setter: (value) => muted = value == 'true' || value == '',
      deleter: () => muted = false
    );
    attributes['volume'] = ElementAttributeProperty(
      getter: () => volume?.toString(),
      setter: (value) => volume = double.tryParse(value) ?? 0.0,
      deleter: () => volume = 0.0
    );
    attributes['playback-rate'] = ElementAttributeProperty(
      getter: () => playbackRate?.toString(),
      setter: (value) => playbackRate = double.tryParse(value) ?? 0.0,
      deleter: () => playbackRate = 0.0
    );
    attributes['current-time'] = ElementAttributeProperty(
      getter: () => currentTime?.toString(),
      setter: (value) => currentTime = double.tryParse(value) ?? 0.0,
      deleter: () => currentTime = 0.0
    );
    attributes['object-fit'] = ElementAttributeProperty(
      getter: () => objectFit?.toString(),
      setter: (value) => objectFit = value,
      deleter: () => objectFit = null
    );
    attributes['preload'] = ElementAttributeProperty(
      getter: () => preload?.toString(),
      setter: (value) => preload = value,
      deleter: () => preload = null
    );
    attributes['plays-inline'] = ElementAttributeProperty(
      getter: () => playsInline.toString(),
      setter: (value) => playsInline = value == 'true' || value == '',
      deleter: () => playsInline = false
    );
    attributes['duration'] = ElementAttributeProperty(
      getter: () => duration?.toString(),
      setter: (value) => duration = double.tryParse(value) ?? 0.0,
      deleter: () => duration = 0.0
    );
    attributes['paused'] = ElementAttributeProperty(
      getter: () => paused.toString(),
      setter: (value) => paused = value == 'true' || value == '',
      deleter: () => paused = false
    );
    attributes['ended'] = ElementAttributeProperty(
      getter: () => ended.toString(),
      setter: (value) => ended = value == 'true' || value == '',
      deleter: () => ended = false
    );
    attributes['seeking'] = ElementAttributeProperty(
      getter: () => seeking.toString(),
      setter: (value) => seeking = value == 'true' || value == '',
      deleter: () => seeking = false
    );
    attributes['ready-state'] = ElementAttributeProperty(
      getter: () => readyState?.toString(),
      setter: (value) => readyState = int.tryParse(value) ?? 0,
      deleter: () => readyState = 0
    );
    attributes['network-state'] = ElementAttributeProperty(
      getter: () => networkState?.toString(),
      setter: (value) => networkState = int.tryParse(value) ?? 0,
      deleter: () => networkState = 0
    );
    attributes['video-width'] = ElementAttributeProperty(
      getter: () => videoWidth?.toString(),
      setter: (value) => videoWidth = int.tryParse(value) ?? 0,
      deleter: () => videoWidth = 0
    );
    attributes['video-height'] = ElementAttributeProperty(
      getter: () => videoHeight?.toString(),
      setter: (value) => videoHeight = int.tryParse(value) ?? 0,
      deleter: () => videoHeight = 0
    );
    attributes['buffering'] = ElementAttributeProperty(
      getter: () => buffering.toString(),
      setter: (value) => buffering = value == 'true' || value == '',
      deleter: () => buffering = false
    );
  }
  static StaticDefinedBindingPropertyMap webFVideoPlayerProperties = {
    'src': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).src,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).src = value,
    ),
    'poster': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).poster,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).poster = value,
    ),
    'autoplay': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).autoplay,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).autoplay = value,
    ),
    'controls': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).controls,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).controls = value,
    ),
    'loop': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).loop,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).loop = value,
    ),
    'muted': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).muted,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).muted = value,
    ),
    'volume': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).volume,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).volume = value,
    ),
    'playbackRate': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).playbackRate,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).playbackRate = value,
    ),
    'currentTime': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).currentTime,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).currentTime = value,
    ),
    'objectFit': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).objectFit,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).objectFit = value,
    ),
    'preload': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).preload,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).preload = value,
    ),
    'playsInline': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).playsInline,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).playsInline = value,
    ),
    'duration': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).duration,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).duration = value,
    ),
    'paused': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).paused,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).paused = value,
    ),
    'ended': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).ended,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).ended = value,
    ),
    'seeking': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).seeking,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).seeking = value,
    ),
    'readyState': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).readyState,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).readyState = value,
    ),
    'networkState': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).networkState,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).networkState = value,
    ),
    'videoWidth': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).videoWidth,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).videoWidth = value,
    ),
    'videoHeight': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).videoHeight,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).videoHeight = value,
    ),
    'buffering': StaticDefinedBindingProperty(
      getter: (element) => castToType<WebFVideoPlayerBindings>(element).buffering,
      setter: (element, value) =>
      castToType<WebFVideoPlayerBindings>(element).buffering = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    webFVideoPlayerProperties,
  ];
}