// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=./webf_cupertino_ui/ --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoContextMenuBindings extends WidgetElement {
  FlutterCupertinoContextMenuBindings(super.context);
  bool get enableHapticFeedback;
  set enableHapticFeedback(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['enable-haptic-feedback'] = ElementAttributeProperty(
      getter: () => enableHapticFeedback.toString(),
      setter: (value) => enableHapticFeedback = value == 'true' || value == '',
      deleter: () => enableHapticFeedback = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoContextMenuProperties = {
    'enableHapticFeedback': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoContextMenuBindings>(element).enableHapticFeedback,
      setter: (element, value) =>
      castToType<FlutterCupertinoContextMenuBindings>(element).enableHapticFeedback = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoContextMenuProperties,
  ];
}