// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=./webf_cupertino_ui/ --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoFormSectionBindings extends WidgetElement {
  FlutterCupertinoFormSectionBindings(super.context);
  String? get insetGrouped;
  set insetGrouped(value);
  String? get clipBehavior;
  set clipBehavior(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['inset-grouped'] = ElementAttributeProperty(
      getter: () => insetGrouped?.toString(),
      setter: (value) => insetGrouped = value,
      deleter: () => insetGrouped = null
    );
    attributes['clip-behavior'] = ElementAttributeProperty(
      getter: () => clipBehavior?.toString(),
      setter: (value) => clipBehavior = value,
      deleter: () => clipBehavior = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoFormSectionProperties = {
    'insetGrouped': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoFormSectionBindings>(element).insetGrouped,
      setter: (element, value) =>
      castToType<FlutterCupertinoFormSectionBindings>(element).insetGrouped = value,
    ),
    'clipBehavior': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoFormSectionBindings>(element).clipBehavior,
      setter: (element, value) =>
      castToType<FlutterCupertinoFormSectionBindings>(element).clipBehavior = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoFormSectionProperties,
  ];
}