// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=./webf_cupertino_ui/ --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoListTileBindings extends WidgetElement {
  FlutterCupertinoListTileBindings(super.context);
  String? get showChevron;
  set showChevron(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['show-chevron'] = ElementAttributeProperty(
      getter: () => showChevron?.toString(),
      setter: (value) => showChevron = value,
      deleter: () => showChevron = null
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoListTileProperties = {
    'showChevron': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoListTileBindings>(element).showChevron,
      setter: (element, value) =>
      castToType<FlutterCupertinoListTileBindings>(element).showChevron = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoListTileProperties,
  ];
}