// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen generate --flutter-package-src=./webf/lib/src/cupertino --framework=<framework> <distPath>
import 'package:webf/webf.dart';
abstract class FlutterCupertinoPickerBindings extends WidgetElement {
  FlutterCupertinoPickerBindings(super.context);
  int? get height;
  set height(value);
  int? get itemHeight;
  set itemHeight(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['height'] = ElementAttributeProperty(
      getter: () => height.toString(),
      setter: (value) => height = value
    );
    attributes['item-height'] = ElementAttributeProperty(
      getter: () => itemHeight.toString(),
      setter: (value) => itemHeight = value
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoPickerProperties = {
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoPickerBindings>(element).height,
      setter: (element, value) =>
      castToType<FlutterCupertinoPickerBindings>(element).height = value,
    ),
    'itemHeight': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoPickerBindings>(element).itemHeight,
      setter: (element, value) =>
      castToType<FlutterCupertinoPickerBindings>(element).itemHeight = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoPickerProperties,
  ];
}