// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=./webf_cupertino_ui/ --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoSearchInputBindings extends WidgetElement {
  FlutterCupertinoSearchInputBindings(super.context);
  String? get val;
  set val(value);
  String? get placeholder;
  set placeholder(value);
  bool get disabled;
  set disabled(value);
  String? get type;
  set type(value);
  String? get prefixIcon;
  set prefixIcon(value);
  String? get suffixIcon;
  set suffixIcon(value);
  String? get suffixModel;
  set suffixModel(value);
  String? get itemColor;
  set itemColor(value);
  double? get itemSize;
  set itemSize(value);
  bool get autofocus;
  set autofocus(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['val'] = ElementAttributeProperty(
      getter: () => val?.toString(),
      setter: (value) => val = value,
      deleter: () => val = null
    );
    attributes['placeholder'] = ElementAttributeProperty(
      getter: () => placeholder?.toString(),
      setter: (value) => placeholder = value,
      deleter: () => placeholder = null
    );
    attributes['disabled'] = ElementAttributeProperty(
      getter: () => disabled.toString(),
      setter: (value) => disabled = value == 'true' || value == '',
      deleter: () => disabled = false
    );
    attributes['type'] = ElementAttributeProperty(
      getter: () => type?.toString(),
      setter: (value) => type = value,
      deleter: () => type = null
    );
    attributes['prefix-icon'] = ElementAttributeProperty(
      getter: () => prefixIcon?.toString(),
      setter: (value) => prefixIcon = value,
      deleter: () => prefixIcon = null
    );
    attributes['suffix-icon'] = ElementAttributeProperty(
      getter: () => suffixIcon?.toString(),
      setter: (value) => suffixIcon = value,
      deleter: () => suffixIcon = null
    );
    attributes['suffix-model'] = ElementAttributeProperty(
      getter: () => suffixModel?.toString(),
      setter: (value) => suffixModel = value,
      deleter: () => suffixModel = null
    );
    attributes['item-color'] = ElementAttributeProperty(
      getter: () => itemColor?.toString(),
      setter: (value) => itemColor = value,
      deleter: () => itemColor = null
    );
    attributes['item-size'] = ElementAttributeProperty(
      getter: () => itemSize?.toString(),
      setter: (value) => itemSize = double.tryParse(value) ?? 0.0,
      deleter: () => itemSize = 0.0
    );
    attributes['autofocus'] = ElementAttributeProperty(
      getter: () => autofocus.toString(),
      setter: (value) => autofocus = value == 'true' || value == '',
      deleter: () => autofocus = false
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoSearchInputProperties = {
    'val': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).val,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).val = value,
    ),
    'placeholder': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).placeholder,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).placeholder = value,
    ),
    'disabled': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).disabled,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).disabled = value,
    ),
    'type': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).type,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).type = value,
    ),
    'prefixIcon': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).prefixIcon,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).prefixIcon = value,
    ),
    'suffixIcon': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).suffixIcon,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).suffixIcon = value,
    ),
    'suffixModel': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).suffixModel,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).suffixModel = value,
    ),
    'itemColor': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).itemColor,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).itemColor = value,
    ),
    'itemSize': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).itemSize,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).itemSize = value,
    ),
    'autofocus': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoSearchInputBindings>(element).autofocus,
      setter: (element, value) =>
      castToType<FlutterCupertinoSearchInputBindings>(element).autofocus = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoSearchInputProperties,
  ];
}