// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=./webf_cupertino_ui/ --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterCupertinoTimerPickerBindings extends WidgetElement {
  FlutterCupertinoTimerPickerBindings(super.context);
  String? get mode;
  set mode(value);
  int? get initialTimerDuration;
  set initialTimerDuration(value);
  int? get minuteInterval;
  set minuteInterval(value);
  int? get secondInterval;
  set secondInterval(value);
  String? get backgroundColor;
  set backgroundColor(value);
  double? get height;
  set height(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['mode'] = ElementAttributeProperty(
      getter: () => mode?.toString(),
      setter: (value) => mode = value,
      deleter: () => mode = null
    );
    attributes['initial-timer-duration'] = ElementAttributeProperty(
      getter: () => initialTimerDuration?.toString(),
      setter: (value) => initialTimerDuration = int.tryParse(value) ?? 0,
      deleter: () => initialTimerDuration = 0
    );
    attributes['minute-interval'] = ElementAttributeProperty(
      getter: () => minuteInterval?.toString(),
      setter: (value) => minuteInterval = int.tryParse(value) ?? 0,
      deleter: () => minuteInterval = 0
    );
    attributes['second-interval'] = ElementAttributeProperty(
      getter: () => secondInterval?.toString(),
      setter: (value) => secondInterval = int.tryParse(value) ?? 0,
      deleter: () => secondInterval = 0
    );
    attributes['background-color'] = ElementAttributeProperty(
      getter: () => backgroundColor?.toString(),
      setter: (value) => backgroundColor = value,
      deleter: () => backgroundColor = null
    );
    attributes['height'] = ElementAttributeProperty(
      getter: () => height?.toString(),
      setter: (value) => height = double.tryParse(value) ?? 0.0,
      deleter: () => height = 0.0
    );
  }
  static StaticDefinedBindingPropertyMap flutterCupertinoTimerPickerProperties = {
    'mode': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoTimerPickerBindings>(element).mode,
      setter: (element, value) =>
      castToType<FlutterCupertinoTimerPickerBindings>(element).mode = value,
    ),
    'initialTimerDuration': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoTimerPickerBindings>(element).initialTimerDuration,
      setter: (element, value) =>
      castToType<FlutterCupertinoTimerPickerBindings>(element).initialTimerDuration = value,
    ),
    'minuteInterval': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoTimerPickerBindings>(element).minuteInterval,
      setter: (element, value) =>
      castToType<FlutterCupertinoTimerPickerBindings>(element).minuteInterval = value,
    ),
    'secondInterval': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoTimerPickerBindings>(element).secondInterval,
      setter: (element, value) =>
      castToType<FlutterCupertinoTimerPickerBindings>(element).secondInterval = value,
    ),
    'backgroundColor': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoTimerPickerBindings>(element).backgroundColor,
      setter: (element, value) =>
      castToType<FlutterCupertinoTimerPickerBindings>(element).backgroundColor = value,
    ),
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterCupertinoTimerPickerBindings>(element).height,
      setter: (element, value) =>
      castToType<FlutterCupertinoTimerPickerBindings>(element).height = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterCupertinoTimerPickerProperties,
  ];
}