// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

/*
 * Copyright (C) 2022-present The WebF authors. All rights reserved.
 */

#ifndef WEBF_CSS_PROPERTY_NAMES_H
#define WEBF_CSS_PROPERTY_NAMES_H

#include <cstddef>
#include <cassert>
#include "bindings/qjs/atomic_string.h"
#include "foundation/macros.h"
#include "css_sample_id.h"

namespace webf {

class ExecutingContext;

enum class CSSPropertyID {
  kInvalid = 0,
  kVariable = 1,
  kColorScheme = 2,
  kForcedColorAdjust = 3,
  kMaskImage = 4,
  kMathDepth = 5,
  kPosition = 6,
  kPositionAnchor = 7,
  kTextSizeAdjust = 8,
  kAppearance = 9,
  kColor = 10,
  kDirection = 11,
  kFontFamily = 12,
  kFontFeatureSettings = 13,
  kFontKerning = 14,
  kFontOpticalSizing = 15,
  kFontPalette = 16,
  kFontSize = 17,
  kFontSizeAdjust = 18,
  kFontStretch = 19,
  kFontStyle = 20,
  kFontSynthesisSmallCaps = 21,
  kFontSynthesisStyle = 22,
  kFontSynthesisWeight = 23,
  kFontVariantAlternates = 24,
  kFontVariantCaps = 25,
  kFontVariantEastAsian = 26,
  kFontVariantEmoji = 27,
  kFontVariantLigatures = 28,
  kFontVariantNumeric = 29,
  kFontVariantPosition = 30,
  kFontVariationSettings = 31,
  kFontWeight = 32,
  kInsetArea = 33,
  kInternalVisitedColor = 34,
  kTextOrientation = 35,
  kTextRendering = 36,
  kTextSpacingTrim = 37,
  kWebkitFontSmoothing = 38,
  kWebkitLocale = 39,
  kWebkitTextOrientation = 40,
  kWebkitWritingMode = 41,
  kWritingMode = 42,
  kZoom = 43,
  kAccentColor = 44,
  kAdditiveSymbols = 45,
  kAlignContent = 46,
  kAlignItems = 47,
  kAlignSelf = 48,
  kAlignmentBaseline = 49,
  kAll = 50,
  kAnchorName = 51,
  kAnchorScope = 52,
  kAnimationComposition = 53,
  kAnimationDelay = 54,
  kAnimationDirection = 55,
  kAnimationDuration = 56,
  kAnimationFillMode = 57,
  kAnimationIterationCount = 58,
  kAnimationName = 59,
  kAnimationPlayState = 60,
  kAnimationRangeEnd = 61,
  kAnimationRangeStart = 62,
  kAnimationTimeline = 63,
  kAnimationTimingFunction = 64,
  kAppRegion = 65,
  kAscentOverride = 66,
  kAspectRatio = 67,
  kBackdropFilter = 68,
  kBackfaceVisibility = 69,
  kBackgroundAttachment = 70,
  kBackgroundBlendMode = 71,
  kBackgroundClip = 72,
  kBackgroundColor = 73,
  kBackgroundImage = 74,
  kBackgroundOrigin = 75,
  kBackgroundPositionX = 76,
  kBackgroundPositionY = 77,
  kBackgroundRepeat = 78,
  kBackgroundSize = 79,
  kBasePalette = 80,
  kBaselineShift = 81,
  kBaselineSource = 82,
  kBlockSize = 83,
  kBorderBlockEndColor = 84,
  kBorderBlockEndStyle = 85,
  kBorderBlockEndWidth = 86,
  kBorderBlockStartColor = 87,
  kBorderBlockStartStyle = 88,
  kBorderBlockStartWidth = 89,
  kBorderBottomColor = 90,
  kBorderBottomLeftRadius = 91,
  kBorderBottomRightRadius = 92,
  kBorderBottomStyle = 93,
  kBorderBottomWidth = 94,
  kBorderCollapse = 95,
  kBorderEndEndRadius = 96,
  kBorderEndStartRadius = 97,
  kBorderImageOutset = 98,
  kBorderImageRepeat = 99,
  kBorderImageSlice = 100,
  kBorderImageSource = 101,
  kBorderImageWidth = 102,
  kBorderInlineEndColor = 103,
  kBorderInlineEndStyle = 104,
  kBorderInlineEndWidth = 105,
  kBorderInlineStartColor = 106,
  kBorderInlineStartStyle = 107,
  kBorderInlineStartWidth = 108,
  kBorderLeftColor = 109,
  kBorderLeftStyle = 110,
  kBorderLeftWidth = 111,
  kBorderRightColor = 112,
  kBorderRightStyle = 113,
  kBorderRightWidth = 114,
  kBorderStartEndRadius = 115,
  kBorderStartStartRadius = 116,
  kBorderTopColor = 117,
  kBorderTopLeftRadius = 118,
  kBorderTopRightRadius = 119,
  kBorderTopStyle = 120,
  kBorderTopWidth = 121,
  kBottom = 122,
  kBoxShadow = 123,
  kBoxSizing = 124,
  kBreakAfter = 125,
  kBreakBefore = 126,
  kBreakInside = 127,
  kBufferedRendering = 128,
  kCaptionSide = 129,
  kCaretColor = 130,
  kClear = 131,
  kClip = 132,
  kClipPath = 133,
  kClipRule = 134,
  kColorInterpolation = 135,
  kColorInterpolationFilters = 136,
  kColorRendering = 137,
  kColumnCount = 138,
  kColumnFill = 139,
  kColumnGap = 140,
  kColumnRuleColor = 141,
  kColumnRuleStyle = 142,
  kColumnRuleWidth = 143,
  kColumnSpan = 144,
  kColumnWidth = 145,
  kContain = 146,
  kContainIntrinsicBlockSize = 147,
  kContainIntrinsicHeight = 148,
  kContainIntrinsicInlineSize = 149,
  kContainIntrinsicWidth = 150,
  kContainerName = 151,
  kContainerType = 152,
  kContent = 153,
  kContentVisibility = 154,
  kCounterIncrement = 155,
  kCounterReset = 156,
  kCounterSet = 157,
  kCursor = 158,
  kCx = 159,
  kCy = 160,
  kD = 161,
  kDescentOverride = 162,
  kDisplay = 163,
  kDominantBaseline = 164,
  kDynamicRangeLimit = 165,
  kEmptyCells = 166,
  kFallback = 167,
  kFieldSizing = 168,
  kFill = 169,
  kFillOpacity = 170,
  kFillRule = 171,
  kFilter = 172,
  kFlexBasis = 173,
  kFlexDirection = 174,
  kFlexGrow = 175,
  kFlexShrink = 176,
  kFlexWrap = 177,
  kFloat = 178,
  kFloodColor = 179,
  kFloodOpacity = 180,
  kFontDisplay = 181,
  kGridAutoColumns = 182,
  kGridAutoFlow = 183,
  kGridAutoRows = 184,
  kGridColumnEnd = 185,
  kGridColumnStart = 186,
  kGridRowEnd = 187,
  kGridRowStart = 188,
  kGridTemplateAreas = 189,
  kGridTemplateColumns = 190,
  kGridTemplateRows = 191,
  kHeight = 192,
  kHyphenateCharacter = 193,
  kHyphenateLimitChars = 194,
  kHyphens = 195,
  kImageOrientation = 196,
  kImageRendering = 197,
  kInherits = 198,
  kInitialLetter = 199,
  kInitialValue = 200,
  kInlineSize = 201,
  kInsetBlockEnd = 202,
  kInsetBlockStart = 203,
  kInsetInlineEnd = 204,
  kInsetInlineStart = 205,
  kInternalAlignContentBlock = 206,
  kInternalEmptyLineHeight = 207,
  kInternalFontSizeDelta = 208,
  kInternalForcedBackgroundColor = 209,
  kInternalForcedBorderColor = 210,
  kInternalForcedColor = 211,
  kInternalForcedOutlineColor = 212,
  kInternalForcedVisitedColor = 213,
  kInternalOverflowBlock = 214,
  kInternalOverflowInline = 215,
  kInternalVisitedBackgroundColor = 216,
  kInternalVisitedBorderBlockEndColor = 217,
  kInternalVisitedBorderBlockStartColor = 218,
  kInternalVisitedBorderBottomColor = 219,
  kInternalVisitedBorderInlineEndColor = 220,
  kInternalVisitedBorderInlineStartColor = 221,
  kInternalVisitedBorderLeftColor = 222,
  kInternalVisitedBorderRightColor = 223,
  kInternalVisitedBorderTopColor = 224,
  kInternalVisitedCaretColor = 225,
  kInternalVisitedColumnRuleColor = 226,
  kInternalVisitedFill = 227,
  kInternalVisitedOutlineColor = 228,
  kInternalVisitedStroke = 229,
  kInternalVisitedTextDecorationColor = 230,
  kInternalVisitedTextEmphasisColor = 231,
  kInternalVisitedTextFillColor = 232,
  kInternalVisitedTextStrokeColor = 233,
  kIsolation = 234,
  kJustifyContent = 235,
  kJustifyItems = 236,
  kJustifySelf = 237,
  kLeft = 238,
  kLetterSpacing = 239,
  kLightingColor = 240,
  kLineBreak = 241,
  kLineClamp = 242,
  kLineGapOverride = 243,
  kLineHeight = 244,
  kListStyleImage = 245,
  kListStylePosition = 246,
  kListStyleType = 247,
  kMarginBlockEnd = 248,
  kMarginBlockStart = 249,
  kMarginBottom = 250,
  kMarginInlineEnd = 251,
  kMarginInlineStart = 252,
  kMarginLeft = 253,
  kMarginRight = 254,
  kMarginTop = 255,
  kMarkerEnd = 256,
  kMarkerMid = 257,
  kMarkerStart = 258,
  kMaskClip = 259,
  kMaskComposite = 260,
  kMaskMode = 261,
  kMaskOrigin = 262,
  kMaskRepeat = 263,
  kMaskSize = 264,
  kMaskType = 265,
  kMathShift = 266,
  kMathStyle = 267,
  kMaxBlockSize = 268,
  kMaxHeight = 269,
  kMaxInlineSize = 270,
  kMaxWidth = 271,
  kMinBlockSize = 272,
  kMinHeight = 273,
  kMinInlineSize = 274,
  kMinWidth = 275,
  kMixBlendMode = 276,
  kNavigation = 277,
  kNegative = 278,
  kObjectFit = 279,
  kObjectPosition = 280,
  kObjectViewBox = 281,
  kOffsetAnchor = 282,
  kOffsetDistance = 283,
  kOffsetPath = 284,
  kOffsetPosition = 285,
  kOffsetRotate = 286,
  kOpacity = 287,
  kOrder = 288,
  kOriginTrialTestProperty = 289,
  kOrphans = 290,
  kOutlineColor = 291,
  kOutlineOffset = 292,
  kOutlineStyle = 293,
  kOutlineWidth = 294,
  kOverflowAnchor = 295,
  kOverflowBlock = 296,
  kOverflowClipMargin = 297,
  kOverflowInline = 298,
  kOverflowWrap = 299,
  kOverflowX = 300,
  kOverflowY = 301,
  kOverlay = 302,
  kOverrideColors = 303,
  kOverscrollBehaviorBlock = 304,
  kOverscrollBehaviorInline = 305,
  kOverscrollBehaviorX = 306,
  kOverscrollBehaviorY = 307,
  kPad = 308,
  kPaddingBlockEnd = 309,
  kPaddingBlockStart = 310,
  kPaddingBottom = 311,
  kPaddingInlineEnd = 312,
  kPaddingInlineStart = 313,
  kPaddingLeft = 314,
  kPaddingRight = 315,
  kPaddingTop = 316,
  kPage = 317,
  kPageOrientation = 318,
  kPaintOrder = 319,
  kPerspective = 320,
  kPerspectiveOrigin = 321,
  kPointerEvents = 322,
  kPopoverHideDelay = 323,
  kPopoverShowDelay = 324,
  kPositionTryOptions = 325,
  kPositionTryOrder = 326,
  kPositionVisibility = 327,
  kPrefix = 328,
  kQuotes = 329,
  kR = 330,
  kRange = 331,
  kReadingOrderItems = 332,
  kResize = 333,
  kRight = 334,
  kRotate = 335,
  kRowGap = 336,
  kRubyAlign = 337,
  kRubyPosition = 338,
  kRx = 339,
  kRy = 340,
  kScale = 341,
  kScrollBehavior = 342,
  kScrollMarginBlockEnd = 343,
  kScrollMarginBlockStart = 344,
  kScrollMarginBottom = 345,
  kScrollMarginInlineEnd = 346,
  kScrollMarginInlineStart = 347,
  kScrollMarginLeft = 348,
  kScrollMarginRight = 349,
  kScrollMarginTop = 350,
  kScrollMarkers = 351,
  kScrollPaddingBlockEnd = 352,
  kScrollPaddingBlockStart = 353,
  kScrollPaddingBottom = 354,
  kScrollPaddingInlineEnd = 355,
  kScrollPaddingInlineStart = 356,
  kScrollPaddingLeft = 357,
  kScrollPaddingRight = 358,
  kScrollPaddingTop = 359,
  kScrollSnapAlign = 360,
  kScrollSnapStop = 361,
  kScrollSnapType = 362,
  kScrollStartBlock = 363,
  kScrollStartInline = 364,
  kScrollStartTargetBlock = 365,
  kScrollStartTargetInline = 366,
  kScrollStartTargetX = 367,
  kScrollStartTargetY = 368,
  kScrollStartX = 369,
  kScrollStartY = 370,
  kScrollTimelineAxis = 371,
  kScrollTimelineName = 372,
  kScrollbarColor = 373,
  kScrollbarGutter = 374,
  kScrollbarWidth = 375,
  kShapeImageThreshold = 376,
  kShapeMargin = 377,
  kShapeOutside = 378,
  kShapeRendering = 379,
  kSize = 380,
  kSizeAdjust = 381,
  kSpeak = 382,
  kSpeakAs = 383,
  kSrc = 384,
  kStopColor = 385,
  kStopOpacity = 386,
  kStroke = 387,
  kStrokeDasharray = 388,
  kStrokeDashoffset = 389,
  kStrokeLinecap = 390,
  kStrokeLinejoin = 391,
  kStrokeMiterlimit = 392,
  kStrokeOpacity = 393,
  kStrokeWidth = 394,
  kSuffix = 395,
  kSymbols = 396,
  kSyntax = 397,
  kSystem = 398,
  kTabSize = 399,
  kTableLayout = 400,
  kTextAlign = 401,
  kTextAlignLast = 402,
  kTextAnchor = 403,
  kTextAutospace = 404,
  kTextBoxEdge = 405,
  kTextBoxTrim = 406,
  kTextCombineUpright = 407,
  kTextDecorationColor = 408,
  kTextDecorationLine = 409,
  kTextDecorationSkipInk = 410,
  kTextDecorationStyle = 411,
  kTextDecorationThickness = 412,
  kTextEmphasisColor = 413,
  kTextEmphasisPosition = 414,
  kTextEmphasisStyle = 415,
  kTextIndent = 416,
  kTextOverflow = 417,
  kTextShadow = 418,
  kTextTransform = 419,
  kTextUnderlineOffset = 420,
  kTextUnderlinePosition = 421,
  kTextWrap = 422,
  kTimelineScope = 423,
  kTop = 424,
  kTouchAction = 425,
  kTransform = 426,
  kTransformBox = 427,
  kTransformOrigin = 428,
  kTransformStyle = 429,
  kTransitionBehavior = 430,
  kTransitionDelay = 431,
  kTransitionDuration = 432,
  kTransitionProperty = 433,
  kTransitionTimingFunction = 434,
  kTranslate = 435,
  kTypes = 436,
  kUnicodeBidi = 437,
  kUnicodeRange = 438,
  kUserSelect = 439,
  kVectorEffect = 440,
  kVerticalAlign = 441,
  kViewTimelineAxis = 442,
  kViewTimelineInset = 443,
  kViewTimelineName = 444,
  kViewTransitionClass = 445,
  kViewTransitionName = 446,
  kVisibility = 447,
  kWebkitBorderHorizontalSpacing = 448,
  kWebkitBorderImage = 449,
  kWebkitBorderVerticalSpacing = 450,
  kWebkitBoxAlign = 451,
  kWebkitBoxDecorationBreak = 452,
  kWebkitBoxDirection = 453,
  kWebkitBoxFlex = 454,
  kWebkitBoxOrdinalGroup = 455,
  kWebkitBoxOrient = 456,
  kWebkitBoxPack = 457,
  kWebkitBoxReflect = 458,
  kWebkitLineBreak = 459,
  kWebkitLineClamp = 460,
  kWebkitMaskBoxImageOutset = 461,
  kWebkitMaskBoxImageRepeat = 462,
  kWebkitMaskBoxImageSlice = 463,
  kWebkitMaskBoxImageSource = 464,
  kWebkitMaskBoxImageWidth = 465,
  kWebkitMaskPositionX = 466,
  kWebkitMaskPositionY = 467,
  kWebkitPerspectiveOriginX = 468,
  kWebkitPerspectiveOriginY = 469,
  kWebkitPrintColorAdjust = 470,
  kWebkitRtlOrdering = 471,
  kWebkitRubyPosition = 472,
  kWebkitTapHighlightColor = 473,
  kWebkitTextCombine = 474,
  kWebkitTextDecorationsInEffect = 475,
  kWebkitTextFillColor = 476,
  kWebkitTextSecurity = 477,
  kWebkitTextStrokeColor = 478,
  kWebkitTextStrokeWidth = 479,
  kWebkitTransformOriginX = 480,
  kWebkitTransformOriginY = 481,
  kWebkitTransformOriginZ = 482,
  kWebkitUserDrag = 483,
  kWebkitUserModify = 484,
  kWhiteSpaceCollapse = 485,
  kWidows = 486,
  kWidth = 487,
  kWillChange = 488,
  kWordBreak = 489,
  kWordSpacing = 490,
  kX = 491,
  kY = 492,
  kZIndex = 493,
  kAlternativeAnimationWithTimeline = 494,
  kAnimation = 495,
  kAnimationRange = 496,
  kBackground = 497,
  kBackgroundPosition = 498,
  kBorder = 499,
  kBorderBlock = 500,
  kBorderBlockColor = 501,
  kBorderBlockEnd = 502,
  kBorderBlockStart = 503,
  kBorderBlockStyle = 504,
  kBorderBlockWidth = 505,
  kBorderBottom = 506,
  kBorderColor = 507,
  kBorderImage = 508,
  kBorderInline = 509,
  kBorderInlineColor = 510,
  kBorderInlineEnd = 511,
  kBorderInlineStart = 512,
  kBorderInlineStyle = 513,
  kBorderInlineWidth = 514,
  kBorderLeft = 515,
  kBorderRadius = 516,
  kBorderRight = 517,
  kBorderSpacing = 518,
  kBorderStyle = 519,
  kBorderTop = 520,
  kBorderWidth = 521,
  kColumnRule = 522,
  kColumns = 523,
  kContainIntrinsicSize = 524,
  kContainer = 525,
  kFlex = 526,
  kFlexFlow = 527,
  kFont = 528,
  kFontSynthesis = 529,
  kFontVariant = 530,
  kGap = 531,
  kGrid = 532,
  kGridArea = 533,
  kGridColumn = 534,
  kGridRow = 535,
  kGridTemplate = 536,
  kInset = 537,
  kInsetBlock = 538,
  kInsetInline = 539,
  kListStyle = 540,
  kMargin = 541,
  kMarginBlock = 542,
  kMarginInline = 543,
  kMarker = 544,
  kMask = 545,
  kMaskPosition = 546,
  kOffset = 547,
  kOutline = 548,
  kOverflow = 549,
  kOverscrollBehavior = 550,
  kPadding = 551,
  kPaddingBlock = 552,
  kPaddingInline = 553,
  kPageBreakAfter = 554,
  kPageBreakBefore = 555,
  kPageBreakInside = 556,
  kPlaceContent = 557,
  kPlaceItems = 558,
  kPlaceSelf = 559,
  kPositionTry = 560,
  kScrollMargin = 561,
  kScrollMarginBlock = 562,
  kScrollMarginInline = 563,
  kScrollPadding = 564,
  kScrollPaddingBlock = 565,
  kScrollPaddingInline = 566,
  kScrollStart = 567,
  kScrollStartTarget = 568,
  kScrollTimeline = 569,
  kTextDecoration = 570,
  kTextEmphasis = 571,
  kTextSpacing = 572,
  kTransition = 573,
  kViewTimeline = 574,
  kWebkitColumnBreakAfter = 575,
  kWebkitColumnBreakBefore = 576,
  kWebkitColumnBreakInside = 577,
  kWebkitMaskBoxImage = 578,
  kWebkitTextStroke = 579,
  kWhiteSpace = 580,
  kAliasWebkitAppearance = 581,
  kAliasWebkitAppRegion = 582,
  kAliasWebkitMaskClip = 583,
  kAliasWebkitMaskComposite = 584,
  kAliasWebkitMaskImage = 585,
  kAliasWebkitMaskOrigin = 586,
  kAliasWebkitMaskRepeat = 587,
  kAliasWebkitMaskSize = 588,
  kAliasWebkitBorderEndColor = 589,
  kAliasWebkitBorderEndStyle = 590,
  kAliasWebkitBorderEndWidth = 591,
  kAliasWebkitBorderStartColor = 592,
  kAliasWebkitBorderStartStyle = 593,
  kAliasWebkitBorderStartWidth = 594,
  kAliasWebkitBorderBeforeColor = 595,
  kAliasWebkitBorderBeforeStyle = 596,
  kAliasWebkitBorderBeforeWidth = 597,
  kAliasWebkitBorderAfterColor = 598,
  kAliasWebkitBorderAfterStyle = 599,
  kAliasWebkitBorderAfterWidth = 600,
  kAliasWebkitMarginEnd = 601,
  kAliasWebkitMarginStart = 602,
  kAliasWebkitMarginBefore = 603,
  kAliasWebkitMarginAfter = 604,
  kAliasWebkitPaddingEnd = 605,
  kAliasWebkitPaddingStart = 606,
  kAliasWebkitPaddingBefore = 607,
  kAliasWebkitPaddingAfter = 608,
  kAliasWebkitLogicalWidth = 609,
  kAliasWebkitLogicalHeight = 610,
  kAliasWebkitMinLogicalWidth = 611,
  kAliasWebkitMinLogicalHeight = 612,
  kAliasWebkitMaxLogicalWidth = 613,
  kAliasWebkitMaxLogicalHeight = 614,
  kAliasWebkitBorderAfter = 615,
  kAliasWebkitBorderBefore = 616,
  kAliasWebkitBorderEnd = 617,
  kAliasWebkitBorderStart = 618,
  kAliasWebkitMask = 619,
  kAliasWebkitMaskPosition = 620,
  kAliasEpubCaptionSide = 621,
  kAliasEpubTextCombine = 622,
  kAliasEpubTextEmphasis = 623,
  kAliasEpubTextEmphasisColor = 624,
  kAliasEpubTextEmphasisStyle = 625,
  kAliasEpubTextOrientation = 626,
  kAliasEpubTextTransform = 627,
  kAliasEpubWordBreak = 628,
  kAliasEpubWritingMode = 629,
  kAliasWebkitAlignContent = 630,
  kAliasWebkitAlignItems = 631,
  kAliasWebkitAlignSelf = 632,
  kAliasWebkitAnimation = 633,
  kAliasWebkitAlternativeAnimationWithTimeline = 634,
  kAliasWebkitAnimationDelay = 635,
  kAliasWebkitAnimationDirection = 636,
  kAliasWebkitAnimationDuration = 637,
  kAliasWebkitAnimationFillMode = 638,
  kAliasWebkitAnimationIterationCount = 639,
  kAliasWebkitAnimationName = 640,
  kAliasWebkitAnimationPlayState = 641,
  kAliasWebkitAnimationTimingFunction = 642,
  kAliasWebkitBackfaceVisibility = 643,
  kAliasWebkitBackgroundClip = 644,
  kAliasWebkitBackgroundOrigin = 645,
  kAliasWebkitBackgroundSize = 646,
  kAliasWebkitBorderBottomLeftRadius = 647,
  kAliasWebkitBorderBottomRightRadius = 648,
  kAliasWebkitBorderRadius = 649,
  kAliasWebkitBorderTopLeftRadius = 650,
  kAliasWebkitBorderTopRightRadius = 651,
  kAliasWebkitBoxShadow = 652,
  kAliasWebkitBoxSizing = 653,
  kAliasWebkitClipPath = 654,
  kAliasWebkitColumnCount = 655,
  kAliasWebkitColumnGap = 656,
  kAliasWebkitColumnRule = 657,
  kAliasWebkitColumnRuleColor = 658,
  kAliasWebkitColumnRuleStyle = 659,
  kAliasWebkitColumnRuleWidth = 660,
  kAliasWebkitColumnSpan = 661,
  kAliasWebkitColumnWidth = 662,
  kAliasWebkitColumns = 663,
  kAliasWebkitFilter = 664,
  kAliasWebkitFlex = 665,
  kAliasWebkitFlexBasis = 666,
  kAliasWebkitFlexDirection = 667,
  kAliasWebkitFlexFlow = 668,
  kAliasWebkitFlexGrow = 669,
  kAliasWebkitFlexShrink = 670,
  kAliasWebkitFlexWrap = 671,
  kAliasWebkitFontFeatureSettings = 672,
  kAliasWebkitHyphenateCharacter = 673,
  kAliasWebkitJustifyContent = 674,
  kAliasWebkitOpacity = 675,
  kAliasWebkitOrder = 676,
  kAliasWebkitPerspective = 677,
  kAliasWebkitPerspectiveOrigin = 678,
  kAliasWebkitShapeImageThreshold = 679,
  kAliasWebkitShapeMargin = 680,
  kAliasWebkitShapeOutside = 681,
  kAliasWebkitTextEmphasis = 682,
  kAliasWebkitTextEmphasisColor = 683,
  kAliasWebkitTextEmphasisPosition = 684,
  kAliasWebkitTextEmphasisStyle = 685,
  kAliasWebkitTextSizeAdjust = 686,
  kAliasWebkitTransform = 687,
  kAliasWebkitTransformOrigin = 688,
  kAliasWebkitTransformStyle = 689,
  kAliasWebkitTransition = 690,
  kAliasWebkitTransitionDelay = 691,
  kAliasWebkitTransitionDuration = 692,
  kAliasWebkitTransitionProperty = 693,
  kAliasWebkitTransitionTimingFunction = 694,
  kAliasWebkitUserSelect = 695,
  kAliasWordWrap = 696,
  kAliasGridColumnGap = 697,
  kAliasGridRowGap = 698,
  kAliasGridGap = 699,
};

const CSSPropertyID kCSSPropertyAliasList[] = {
    CSSPropertyID::kAliasWebkitAppearance,
    CSSPropertyID::kAliasWebkitAppRegion,
    CSSPropertyID::kAliasWebkitMaskClip,
    CSSPropertyID::kAliasWebkitMaskComposite,
    CSSPropertyID::kAliasWebkitMaskImage,
    CSSPropertyID::kAliasWebkitMaskOrigin,
    CSSPropertyID::kAliasWebkitMaskRepeat,
    CSSPropertyID::kAliasWebkitMaskSize,
    CSSPropertyID::kAliasWebkitBorderEndColor,
    CSSPropertyID::kAliasWebkitBorderEndStyle,
    CSSPropertyID::kAliasWebkitBorderEndWidth,
    CSSPropertyID::kAliasWebkitBorderStartColor,
    CSSPropertyID::kAliasWebkitBorderStartStyle,
    CSSPropertyID::kAliasWebkitBorderStartWidth,
    CSSPropertyID::kAliasWebkitBorderBeforeColor,
    CSSPropertyID::kAliasWebkitBorderBeforeStyle,
    CSSPropertyID::kAliasWebkitBorderBeforeWidth,
    CSSPropertyID::kAliasWebkitBorderAfterColor,
    CSSPropertyID::kAliasWebkitBorderAfterStyle,
    CSSPropertyID::kAliasWebkitBorderAfterWidth,
    CSSPropertyID::kAliasWebkitMarginEnd,
    CSSPropertyID::kAliasWebkitMarginStart,
    CSSPropertyID::kAliasWebkitMarginBefore,
    CSSPropertyID::kAliasWebkitMarginAfter,
    CSSPropertyID::kAliasWebkitPaddingEnd,
    CSSPropertyID::kAliasWebkitPaddingStart,
    CSSPropertyID::kAliasWebkitPaddingBefore,
    CSSPropertyID::kAliasWebkitPaddingAfter,
    CSSPropertyID::kAliasWebkitLogicalWidth,
    CSSPropertyID::kAliasWebkitLogicalHeight,
    CSSPropertyID::kAliasWebkitMinLogicalWidth,
    CSSPropertyID::kAliasWebkitMinLogicalHeight,
    CSSPropertyID::kAliasWebkitMaxLogicalWidth,
    CSSPropertyID::kAliasWebkitMaxLogicalHeight,
    CSSPropertyID::kAliasWebkitBorderAfter,
    CSSPropertyID::kAliasWebkitBorderBefore,
    CSSPropertyID::kAliasWebkitBorderEnd,
    CSSPropertyID::kAliasWebkitBorderStart,
    CSSPropertyID::kAliasWebkitMask,
    CSSPropertyID::kAliasWebkitMaskPosition,
    CSSPropertyID::kAliasEpubCaptionSide,
    CSSPropertyID::kAliasEpubTextCombine,
    CSSPropertyID::kAliasEpubTextEmphasis,
    CSSPropertyID::kAliasEpubTextEmphasisColor,
    CSSPropertyID::kAliasEpubTextEmphasisStyle,
    CSSPropertyID::kAliasEpubTextOrientation,
    CSSPropertyID::kAliasEpubTextTransform,
    CSSPropertyID::kAliasEpubWordBreak,
    CSSPropertyID::kAliasEpubWritingMode,
    CSSPropertyID::kAliasWebkitAlignContent,
    CSSPropertyID::kAliasWebkitAlignItems,
    CSSPropertyID::kAliasWebkitAlignSelf,
    CSSPropertyID::kAliasWebkitAnimation,
    CSSPropertyID::kAliasWebkitAlternativeAnimationWithTimeline,
    CSSPropertyID::kAliasWebkitAnimationDelay,
    CSSPropertyID::kAliasWebkitAnimationDirection,
    CSSPropertyID::kAliasWebkitAnimationDuration,
    CSSPropertyID::kAliasWebkitAnimationFillMode,
    CSSPropertyID::kAliasWebkitAnimationIterationCount,
    CSSPropertyID::kAliasWebkitAnimationName,
    CSSPropertyID::kAliasWebkitAnimationPlayState,
    CSSPropertyID::kAliasWebkitAnimationTimingFunction,
    CSSPropertyID::kAliasWebkitBackfaceVisibility,
    CSSPropertyID::kAliasWebkitBackgroundClip,
    CSSPropertyID::kAliasWebkitBackgroundOrigin,
    CSSPropertyID::kAliasWebkitBackgroundSize,
    CSSPropertyID::kAliasWebkitBorderBottomLeftRadius,
    CSSPropertyID::kAliasWebkitBorderBottomRightRadius,
    CSSPropertyID::kAliasWebkitBorderRadius,
    CSSPropertyID::kAliasWebkitBorderTopLeftRadius,
    CSSPropertyID::kAliasWebkitBorderTopRightRadius,
    CSSPropertyID::kAliasWebkitBoxShadow,
    CSSPropertyID::kAliasWebkitBoxSizing,
    CSSPropertyID::kAliasWebkitClipPath,
    CSSPropertyID::kAliasWebkitColumnCount,
    CSSPropertyID::kAliasWebkitColumnGap,
    CSSPropertyID::kAliasWebkitColumnRule,
    CSSPropertyID::kAliasWebkitColumnRuleColor,
    CSSPropertyID::kAliasWebkitColumnRuleStyle,
    CSSPropertyID::kAliasWebkitColumnRuleWidth,
    CSSPropertyID::kAliasWebkitColumnSpan,
    CSSPropertyID::kAliasWebkitColumnWidth,
    CSSPropertyID::kAliasWebkitColumns,
    CSSPropertyID::kAliasWebkitFilter,
    CSSPropertyID::kAliasWebkitFlex,
    CSSPropertyID::kAliasWebkitFlexBasis,
    CSSPropertyID::kAliasWebkitFlexDirection,
    CSSPropertyID::kAliasWebkitFlexFlow,
    CSSPropertyID::kAliasWebkitFlexGrow,
    CSSPropertyID::kAliasWebkitFlexShrink,
    CSSPropertyID::kAliasWebkitFlexWrap,
    CSSPropertyID::kAliasWebkitFontFeatureSettings,
    CSSPropertyID::kAliasWebkitHyphenateCharacter,
    CSSPropertyID::kAliasWebkitJustifyContent,
    CSSPropertyID::kAliasWebkitOpacity,
    CSSPropertyID::kAliasWebkitOrder,
    CSSPropertyID::kAliasWebkitPerspective,
    CSSPropertyID::kAliasWebkitPerspectiveOrigin,
    CSSPropertyID::kAliasWebkitShapeImageThreshold,
    CSSPropertyID::kAliasWebkitShapeMargin,
    CSSPropertyID::kAliasWebkitShapeOutside,
    CSSPropertyID::kAliasWebkitTextEmphasis,
    CSSPropertyID::kAliasWebkitTextEmphasisColor,
    CSSPropertyID::kAliasWebkitTextEmphasisPosition,
    CSSPropertyID::kAliasWebkitTextEmphasisStyle,
    CSSPropertyID::kAliasWebkitTextSizeAdjust,
    CSSPropertyID::kAliasWebkitTransform,
    CSSPropertyID::kAliasWebkitTransformOrigin,
    CSSPropertyID::kAliasWebkitTransformStyle,
    CSSPropertyID::kAliasWebkitTransition,
    CSSPropertyID::kAliasWebkitTransitionDelay,
    CSSPropertyID::kAliasWebkitTransitionDuration,
    CSSPropertyID::kAliasWebkitTransitionProperty,
    CSSPropertyID::kAliasWebkitTransitionTimingFunction,
    CSSPropertyID::kAliasWebkitUserSelect,
    CSSPropertyID::kAliasWordWrap,
    CSSPropertyID::kAliasGridColumnGap,
    CSSPropertyID::kAliasGridRowGap,
    CSSPropertyID::kAliasGridGap,
};

const CSSPropertyID kCSSComputableProperties[] = {
    CSSPropertyID::kAccentColor,
    CSSPropertyID::kAlignContent,
    CSSPropertyID::kAlignItems,
    CSSPropertyID::kAlignSelf,
    CSSPropertyID::kAlignmentBaseline,
    CSSPropertyID::kAnchorName,
    CSSPropertyID::kAnchorScope,
    CSSPropertyID::kAnimationComposition,
    CSSPropertyID::kAnimationDelay,
    CSSPropertyID::kAnimationDirection,
    CSSPropertyID::kAnimationDuration,
    CSSPropertyID::kAnimationFillMode,
    CSSPropertyID::kAnimationIterationCount,
    CSSPropertyID::kAnimationName,
    CSSPropertyID::kAnimationPlayState,
    CSSPropertyID::kAnimationRangeEnd,
    CSSPropertyID::kAnimationRangeStart,
    CSSPropertyID::kAnimationTimeline,
    CSSPropertyID::kAnimationTimingFunction,
    CSSPropertyID::kAppRegion,
    CSSPropertyID::kAppearance,
    CSSPropertyID::kBackdropFilter,
    CSSPropertyID::kBackfaceVisibility,
    CSSPropertyID::kBackgroundAttachment,
    CSSPropertyID::kBackgroundBlendMode,
    CSSPropertyID::kBackgroundClip,
    CSSPropertyID::kBackgroundColor,
    CSSPropertyID::kBackgroundImage,
    CSSPropertyID::kBackgroundOrigin,
    CSSPropertyID::kBackgroundPosition,
    CSSPropertyID::kBackgroundRepeat,
    CSSPropertyID::kBackgroundSize,
    CSSPropertyID::kBaselineShift,
    CSSPropertyID::kBaselineSource,
    CSSPropertyID::kBlockSize,
    CSSPropertyID::kBorderBlockEndColor,
    CSSPropertyID::kBorderBlockEndStyle,
    CSSPropertyID::kBorderBlockEndWidth,
    CSSPropertyID::kBorderBlockStartColor,
    CSSPropertyID::kBorderBlockStartStyle,
    CSSPropertyID::kBorderBlockStartWidth,
    CSSPropertyID::kBorderBottomColor,
    CSSPropertyID::kBorderBottomLeftRadius,
    CSSPropertyID::kBorderBottomRightRadius,
    CSSPropertyID::kBorderBottomStyle,
    CSSPropertyID::kBorderBottomWidth,
    CSSPropertyID::kBorderCollapse,
    CSSPropertyID::kBorderEndEndRadius,
    CSSPropertyID::kBorderEndStartRadius,
    CSSPropertyID::kBorderImageOutset,
    CSSPropertyID::kBorderImageRepeat,
    CSSPropertyID::kBorderImageSlice,
    CSSPropertyID::kBorderImageSource,
    CSSPropertyID::kBorderImageWidth,
    CSSPropertyID::kBorderInlineEndColor,
    CSSPropertyID::kBorderInlineEndStyle,
    CSSPropertyID::kBorderInlineEndWidth,
    CSSPropertyID::kBorderInlineStartColor,
    CSSPropertyID::kBorderInlineStartStyle,
    CSSPropertyID::kBorderInlineStartWidth,
    CSSPropertyID::kBorderLeftColor,
    CSSPropertyID::kBorderLeftStyle,
    CSSPropertyID::kBorderLeftWidth,
    CSSPropertyID::kBorderRightColor,
    CSSPropertyID::kBorderRightStyle,
    CSSPropertyID::kBorderRightWidth,
    CSSPropertyID::kBorderStartEndRadius,
    CSSPropertyID::kBorderStartStartRadius,
    CSSPropertyID::kBorderTopColor,
    CSSPropertyID::kBorderTopLeftRadius,
    CSSPropertyID::kBorderTopRightRadius,
    CSSPropertyID::kBorderTopStyle,
    CSSPropertyID::kBorderTopWidth,
    CSSPropertyID::kBottom,
    CSSPropertyID::kBoxShadow,
    CSSPropertyID::kBoxSizing,
    CSSPropertyID::kBreakAfter,
    CSSPropertyID::kBreakBefore,
    CSSPropertyID::kBreakInside,
    CSSPropertyID::kBufferedRendering,
    CSSPropertyID::kCaptionSide,
    CSSPropertyID::kCaretColor,
    CSSPropertyID::kClear,
    CSSPropertyID::kClip,
    CSSPropertyID::kClipPath,
    CSSPropertyID::kClipRule,
    CSSPropertyID::kColor,
    CSSPropertyID::kColorInterpolation,
    CSSPropertyID::kColorInterpolationFilters,
    CSSPropertyID::kColorRendering,
    CSSPropertyID::kColumnCount,
    CSSPropertyID::kColumnGap,
    CSSPropertyID::kColumnRuleColor,
    CSSPropertyID::kColumnRuleStyle,
    CSSPropertyID::kColumnRuleWidth,
    CSSPropertyID::kColumnSpan,
    CSSPropertyID::kColumnWidth,
    CSSPropertyID::kContainIntrinsicBlockSize,
    CSSPropertyID::kContainIntrinsicHeight,
    CSSPropertyID::kContainIntrinsicInlineSize,
    CSSPropertyID::kContainIntrinsicSize,
    CSSPropertyID::kContainIntrinsicWidth,
    CSSPropertyID::kContainerName,
    CSSPropertyID::kContainerType,
    CSSPropertyID::kContent,
    CSSPropertyID::kCursor,
    CSSPropertyID::kCx,
    CSSPropertyID::kCy,
    CSSPropertyID::kD,
    CSSPropertyID::kDirection,
    CSSPropertyID::kDisplay,
    CSSPropertyID::kDominantBaseline,
    CSSPropertyID::kDynamicRangeLimit,
    CSSPropertyID::kEmptyCells,
    CSSPropertyID::kFieldSizing,
    CSSPropertyID::kFill,
    CSSPropertyID::kFillOpacity,
    CSSPropertyID::kFillRule,
    CSSPropertyID::kFilter,
    CSSPropertyID::kFlexBasis,
    CSSPropertyID::kFlexDirection,
    CSSPropertyID::kFlexGrow,
    CSSPropertyID::kFlexShrink,
    CSSPropertyID::kFlexWrap,
    CSSPropertyID::kFloat,
    CSSPropertyID::kFloodColor,
    CSSPropertyID::kFloodOpacity,
    CSSPropertyID::kFontFamily,
    CSSPropertyID::kFontKerning,
    CSSPropertyID::kFontOpticalSizing,
    CSSPropertyID::kFontPalette,
    CSSPropertyID::kFontSize,
    CSSPropertyID::kFontSizeAdjust,
    CSSPropertyID::kFontStretch,
    CSSPropertyID::kFontStyle,
    CSSPropertyID::kFontSynthesisSmallCaps,
    CSSPropertyID::kFontSynthesisStyle,
    CSSPropertyID::kFontSynthesisWeight,
    CSSPropertyID::kFontVariant,
    CSSPropertyID::kFontVariantAlternates,
    CSSPropertyID::kFontVariantCaps,
    CSSPropertyID::kFontVariantEastAsian,
    CSSPropertyID::kFontVariantEmoji,
    CSSPropertyID::kFontVariantLigatures,
    CSSPropertyID::kFontVariantNumeric,
    CSSPropertyID::kFontVariantPosition,
    CSSPropertyID::kFontWeight,
    CSSPropertyID::kGridAutoColumns,
    CSSPropertyID::kGridAutoFlow,
    CSSPropertyID::kGridAutoRows,
    CSSPropertyID::kGridColumnEnd,
    CSSPropertyID::kGridColumnStart,
    CSSPropertyID::kGridRowEnd,
    CSSPropertyID::kGridRowStart,
    CSSPropertyID::kGridTemplateAreas,
    CSSPropertyID::kGridTemplateColumns,
    CSSPropertyID::kGridTemplateRows,
    CSSPropertyID::kHeight,
    CSSPropertyID::kHyphenateCharacter,
    CSSPropertyID::kHyphenateLimitChars,
    CSSPropertyID::kHyphens,
    CSSPropertyID::kImageOrientation,
    CSSPropertyID::kImageRendering,
    CSSPropertyID::kInitialLetter,
    CSSPropertyID::kInlineSize,
    CSSPropertyID::kInsetArea,
    CSSPropertyID::kInsetBlockEnd,
    CSSPropertyID::kInsetBlockStart,
    CSSPropertyID::kInsetInlineEnd,
    CSSPropertyID::kInsetInlineStart,
    CSSPropertyID::kIsolation,
    CSSPropertyID::kJustifyContent,
    CSSPropertyID::kJustifyItems,
    CSSPropertyID::kJustifySelf,
    CSSPropertyID::kLeft,
    CSSPropertyID::kLetterSpacing,
    CSSPropertyID::kLightingColor,
    CSSPropertyID::kLineBreak,
    CSSPropertyID::kLineClamp,
    CSSPropertyID::kLineHeight,
    CSSPropertyID::kListStyleImage,
    CSSPropertyID::kListStylePosition,
    CSSPropertyID::kListStyleType,
    CSSPropertyID::kMarginBlockEnd,
    CSSPropertyID::kMarginBlockStart,
    CSSPropertyID::kMarginBottom,
    CSSPropertyID::kMarginInlineEnd,
    CSSPropertyID::kMarginInlineStart,
    CSSPropertyID::kMarginLeft,
    CSSPropertyID::kMarginRight,
    CSSPropertyID::kMarginTop,
    CSSPropertyID::kMarkerEnd,
    CSSPropertyID::kMarkerMid,
    CSSPropertyID::kMarkerStart,
    CSSPropertyID::kMaskClip,
    CSSPropertyID::kMaskComposite,
    CSSPropertyID::kMaskImage,
    CSSPropertyID::kMaskMode,
    CSSPropertyID::kMaskOrigin,
    CSSPropertyID::kMaskPosition,
    CSSPropertyID::kMaskRepeat,
    CSSPropertyID::kMaskSize,
    CSSPropertyID::kMaskType,
    CSSPropertyID::kMathDepth,
    CSSPropertyID::kMathShift,
    CSSPropertyID::kMathStyle,
    CSSPropertyID::kMaxBlockSize,
    CSSPropertyID::kMaxHeight,
    CSSPropertyID::kMaxInlineSize,
    CSSPropertyID::kMaxWidth,
    CSSPropertyID::kMinBlockSize,
    CSSPropertyID::kMinHeight,
    CSSPropertyID::kMinInlineSize,
    CSSPropertyID::kMinWidth,
    CSSPropertyID::kMixBlendMode,
    CSSPropertyID::kObjectFit,
    CSSPropertyID::kObjectPosition,
    CSSPropertyID::kObjectViewBox,
    CSSPropertyID::kOffsetAnchor,
    CSSPropertyID::kOffsetDistance,
    CSSPropertyID::kOffsetPath,
    CSSPropertyID::kOffsetPosition,
    CSSPropertyID::kOffsetRotate,
    CSSPropertyID::kOpacity,
    CSSPropertyID::kOrder,
    CSSPropertyID::kOrphans,
    CSSPropertyID::kOutlineColor,
    CSSPropertyID::kOutlineOffset,
    CSSPropertyID::kOutlineStyle,
    CSSPropertyID::kOutlineWidth,
    CSSPropertyID::kOverflowAnchor,
    CSSPropertyID::kOverflowBlock,
    CSSPropertyID::kOverflowClipMargin,
    CSSPropertyID::kOverflowInline,
    CSSPropertyID::kOverflowWrap,
    CSSPropertyID::kOverflowX,
    CSSPropertyID::kOverflowY,
    CSSPropertyID::kOverlay,
    CSSPropertyID::kOverscrollBehaviorBlock,
    CSSPropertyID::kOverscrollBehaviorInline,
    CSSPropertyID::kPaddingBlockEnd,
    CSSPropertyID::kPaddingBlockStart,
    CSSPropertyID::kPaddingBottom,
    CSSPropertyID::kPaddingInlineEnd,
    CSSPropertyID::kPaddingInlineStart,
    CSSPropertyID::kPaddingLeft,
    CSSPropertyID::kPaddingRight,
    CSSPropertyID::kPaddingTop,
    CSSPropertyID::kPaintOrder,
    CSSPropertyID::kPerspective,
    CSSPropertyID::kPerspectiveOrigin,
    CSSPropertyID::kPointerEvents,
    CSSPropertyID::kPopoverHideDelay,
    CSSPropertyID::kPopoverShowDelay,
    CSSPropertyID::kPosition,
    CSSPropertyID::kPositionAnchor,
    CSSPropertyID::kPositionTryOptions,
    CSSPropertyID::kPositionTryOrder,
    CSSPropertyID::kPositionVisibility,
    CSSPropertyID::kR,
    CSSPropertyID::kReadingOrderItems,
    CSSPropertyID::kResize,
    CSSPropertyID::kRight,
    CSSPropertyID::kRotate,
    CSSPropertyID::kRowGap,
    CSSPropertyID::kRubyAlign,
    CSSPropertyID::kRubyPosition,
    CSSPropertyID::kRx,
    CSSPropertyID::kRy,
    CSSPropertyID::kScale,
    CSSPropertyID::kScrollBehavior,
    CSSPropertyID::kScrollMarginBlockEnd,
    CSSPropertyID::kScrollMarginBlockStart,
    CSSPropertyID::kScrollMarginInlineEnd,
    CSSPropertyID::kScrollMarginInlineStart,
    CSSPropertyID::kScrollMarkers,
    CSSPropertyID::kScrollPaddingBlockEnd,
    CSSPropertyID::kScrollPaddingBlockStart,
    CSSPropertyID::kScrollPaddingInlineEnd,
    CSSPropertyID::kScrollPaddingInlineStart,
    CSSPropertyID::kScrollStartBlock,
    CSSPropertyID::kScrollStartInline,
    CSSPropertyID::kScrollStartTargetBlock,
    CSSPropertyID::kScrollStartTargetInline,
    CSSPropertyID::kScrollStartTargetX,
    CSSPropertyID::kScrollStartTargetY,
    CSSPropertyID::kScrollStartX,
    CSSPropertyID::kScrollStartY,
    CSSPropertyID::kScrollTimelineAxis,
    CSSPropertyID::kScrollTimelineName,
    CSSPropertyID::kScrollbarColor,
    CSSPropertyID::kScrollbarGutter,
    CSSPropertyID::kScrollbarWidth,
    CSSPropertyID::kShapeImageThreshold,
    CSSPropertyID::kShapeMargin,
    CSSPropertyID::kShapeOutside,
    CSSPropertyID::kShapeRendering,
    CSSPropertyID::kSpeak,
    CSSPropertyID::kStopColor,
    CSSPropertyID::kStopOpacity,
    CSSPropertyID::kStroke,
    CSSPropertyID::kStrokeDasharray,
    CSSPropertyID::kStrokeDashoffset,
    CSSPropertyID::kStrokeLinecap,
    CSSPropertyID::kStrokeLinejoin,
    CSSPropertyID::kStrokeMiterlimit,
    CSSPropertyID::kStrokeOpacity,
    CSSPropertyID::kStrokeWidth,
    CSSPropertyID::kTabSize,
    CSSPropertyID::kTableLayout,
    CSSPropertyID::kTextAlign,
    CSSPropertyID::kTextAlignLast,
    CSSPropertyID::kTextAnchor,
    CSSPropertyID::kTextAutospace,
    CSSPropertyID::kTextBoxEdge,
    CSSPropertyID::kTextBoxTrim,
    CSSPropertyID::kTextDecoration,
    CSSPropertyID::kTextDecorationColor,
    CSSPropertyID::kTextDecorationLine,
    CSSPropertyID::kTextDecorationSkipInk,
    CSSPropertyID::kTextDecorationStyle,
    CSSPropertyID::kTextEmphasisColor,
    CSSPropertyID::kTextEmphasisPosition,
    CSSPropertyID::kTextEmphasisStyle,
    CSSPropertyID::kTextIndent,
    CSSPropertyID::kTextOverflow,
    CSSPropertyID::kTextRendering,
    CSSPropertyID::kTextShadow,
    CSSPropertyID::kTextSizeAdjust,
    CSSPropertyID::kTextSpacingTrim,
    CSSPropertyID::kTextTransform,
    CSSPropertyID::kTextUnderlinePosition,
    CSSPropertyID::kTextWrap,
    CSSPropertyID::kTimelineScope,
    CSSPropertyID::kTop,
    CSSPropertyID::kTouchAction,
    CSSPropertyID::kTransform,
    CSSPropertyID::kTransformOrigin,
    CSSPropertyID::kTransformStyle,
    CSSPropertyID::kTransitionBehavior,
    CSSPropertyID::kTransitionDelay,
    CSSPropertyID::kTransitionDuration,
    CSSPropertyID::kTransitionProperty,
    CSSPropertyID::kTransitionTimingFunction,
    CSSPropertyID::kTranslate,
    CSSPropertyID::kUnicodeBidi,
    CSSPropertyID::kUserSelect,
    CSSPropertyID::kVectorEffect,
    CSSPropertyID::kVerticalAlign,
    CSSPropertyID::kViewTimelineAxis,
    CSSPropertyID::kViewTimelineInset,
    CSSPropertyID::kViewTimelineName,
    CSSPropertyID::kViewTransitionClass,
    CSSPropertyID::kViewTransitionName,
    CSSPropertyID::kVisibility,
    CSSPropertyID::kWhiteSpaceCollapse,
    CSSPropertyID::kWidows,
    CSSPropertyID::kWidth,
    CSSPropertyID::kWillChange,
    CSSPropertyID::kWordBreak,
    CSSPropertyID::kWordSpacing,
    CSSPropertyID::kWritingMode,
    CSSPropertyID::kX,
    CSSPropertyID::kY,
    CSSPropertyID::kZIndex,
    CSSPropertyID::kZoom,
    CSSPropertyID::kWebkitBorderHorizontalSpacing,
    CSSPropertyID::kWebkitBorderImage,
    CSSPropertyID::kWebkitBorderVerticalSpacing,
    CSSPropertyID::kWebkitBoxAlign,
    CSSPropertyID::kWebkitBoxDecorationBreak,
    CSSPropertyID::kWebkitBoxDirection,
    CSSPropertyID::kWebkitBoxFlex,
    CSSPropertyID::kWebkitBoxOrdinalGroup,
    CSSPropertyID::kWebkitBoxOrient,
    CSSPropertyID::kWebkitBoxPack,
    CSSPropertyID::kWebkitBoxReflect,
    CSSPropertyID::kWebkitFontSmoothing,
    CSSPropertyID::kWebkitLineBreak,
    CSSPropertyID::kWebkitLineClamp,
    CSSPropertyID::kWebkitLocale,
    CSSPropertyID::kWebkitMaskBoxImage,
    CSSPropertyID::kWebkitMaskBoxImageOutset,
    CSSPropertyID::kWebkitMaskBoxImageRepeat,
    CSSPropertyID::kWebkitMaskBoxImageSlice,
    CSSPropertyID::kWebkitMaskBoxImageSource,
    CSSPropertyID::kWebkitMaskBoxImageWidth,
    CSSPropertyID::kWebkitPrintColorAdjust,
    CSSPropertyID::kWebkitRtlOrdering,
    CSSPropertyID::kWebkitTapHighlightColor,
    CSSPropertyID::kWebkitTextCombine,
    CSSPropertyID::kWebkitTextDecorationsInEffect,
    CSSPropertyID::kWebkitTextFillColor,
    CSSPropertyID::kWebkitTextOrientation,
    CSSPropertyID::kWebkitTextSecurity,
    CSSPropertyID::kWebkitTextStrokeColor,
    CSSPropertyID::kWebkitTextStrokeWidth,
    CSSPropertyID::kWebkitUserDrag,
    CSSPropertyID::kWebkitUserModify,
    CSSPropertyID::kWebkitWritingMode,
};

// The lowest CSSPropertyID excluding kInvalid and kVariable.
const int kIntFirstCSSProperty = 2;
const CSSPropertyID kFirstCSSProperty =
    static_cast<CSSPropertyID>(kIntFirstCSSProperty);

// The number of unresolved CSS properties excluding kInvalid and kVariable.
const int kNumCSSProperties = 698;

// The highest resolved CSSPropertyID.
const int kIntLastCSSProperty = 580;
const CSSPropertyID kLastCSSProperty =
    static_cast<CSSPropertyID>(kIntLastCSSProperty);

// The highest unresolved CSSPropertyID.
const CSSPropertyID kLastUnresolvedCSSProperty =
    static_cast<CSSPropertyID>(699);

const CSSPropertyID kFirstHighPriorityCSSProperty = kFirstCSSProperty;
const CSSPropertyID kLastHighPriorityCSSProperty = CSSPropertyID::kZoom;

// 1 + <The highest unresolved CSSPropertyID>.
const int kNumCSSPropertyIDs = static_cast<int>(kLastUnresolvedCSSProperty) + 1;

const size_t kMaxCSSPropertyNameLength = 48;
constexpr size_t kCSSPropertyIDBitLength = 10;
constexpr size_t kMaxShorthandExpansion = 18;

static_assert((static_cast<size_t>(1) << kCSSPropertyIDBitLength) >
                  static_cast<size_t>(kLastUnresolvedCSSProperty),
              "kCSSPropertyIDBitLength has enough bits");

// These are basically just change-detector tests, so that we do not
// accidentally add new high-priority properties or break the code generator.
static_assert(CSSPropertyID::kColorScheme == kFirstHighPriorityCSSProperty);
static_assert(CSSPropertyID::kZoom == kLastHighPriorityCSSProperty);
static_assert((static_cast<int>(kLastHighPriorityCSSProperty) -
               static_cast<int>(kFirstHighPriorityCSSProperty)) == 41,
              "There should a low number of high-priority properties");

inline int GetCSSPropertyIDIndex(CSSPropertyID id) {
  assert(id >= kFirstCSSProperty);
  assert(id <= kLastCSSProperty);
  return static_cast<int>(id) - kIntFirstCSSProperty;
}

constexpr bool IsHighPriority(CSSPropertyID id) {
  return id >= kFirstHighPriorityCSSProperty &&
         id <= kLastHighPriorityCSSProperty;
}

inline bool IsCSSPropertyIDWithName(CSSPropertyID id)
{
  return id >= kFirstCSSProperty && id <= kLastUnresolvedCSSProperty;
}

inline bool IsValidCSSPropertyID(CSSPropertyID id)
{
  return id != CSSPropertyID::kInvalid;
}

inline CSSPropertyID ConvertToCSSPropertyID(int value)
{
  assert(value >= static_cast<int>(CSSPropertyID::kInvalid));
  assert(value <= kIntLastCSSProperty);
  return static_cast<CSSPropertyID>(value);
}

int ResolveCSSPropertyAlias(int value);

inline bool IsPropertyAlias(CSSPropertyID id) {
  return static_cast<int>(id) >= 581;
}

inline CSSPropertyID ResolveCSSPropertyID(CSSPropertyID id)
{
  int int_id = static_cast<int>(id);
  if (IsPropertyAlias(id))
    int_id = ResolveCSSPropertyAlias(int_id);
  return ConvertToCSSPropertyID(int_id);
}

CSSPropertyID CssPropertyID(const ExecutingContext*,
                                        const AtomicString&);

class CSSPropertyIDList {
  WEBF_STACK_ALLOCATED();

 public:
  class Iterator {
    WEBF_STACK_ALLOCATED();
   public:
    Iterator(int id) : id_(id) {}
    CSSPropertyID operator*() const { return ConvertToCSSPropertyID(id_); }
    Iterator& operator++() {
      id_++;
      return *this;
    }
    bool operator!=(const Iterator& i) const { return id_ != i.id_; }

   private:
    int id_;
  };
  Iterator begin() const { return Iterator(kIntFirstCSSProperty); }
  Iterator end() const { return Iterator(kIntLastCSSProperty + 1); }
};

CSSSampleId GetCSSSampleId(CSSPropertyID id);

}  // namespace webf

#endif  // WEBF_CSS_PROPERTY_NAMES_H
