// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by webf codegen --flutter-package-src=../webf_modules/ui_kit --framework=react <distPath>
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class FlutterIconBindings extends WidgetElement {
  FlutterIconBindings(super.context);
  String get type;
  set type(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['type'] = ElementAttributeProperty(
      getter: () => type.toString(),
      setter: (value) => type = value,
      deleter: () => type = ''
    );
  }
  static StaticDefinedBindingPropertyMap flutterIconProperties = {
    'type': StaticDefinedBindingProperty(
      getter: (element) => castToType<FlutterIconBindings>(element).type,
      setter: (element, value) =>
      castToType<FlutterIconBindings>(element).type = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    flutterIconProperties,
  ];
}